-- Reviewed ownership/contract evidence; idempotent append-only revision; existing controls preserved.
INSERT OR IGNORE INTO countries (id,name,country_code,indicative_region,region_selection_claim_id) VALUES ('IRL','Ireland','IRL','Greater Dublin','C14');
--> statement-breakpoint
INSERT OR IGNORE INTO countries (id,name,country_code,indicative_region,region_selection_claim_id) VALUES ('FIN','Finland','FIN','Helsinki / Uusimaa','C15');
--> statement-breakpoint
INSERT OR IGNORE INTO countries (id,name,country_code,indicative_region,region_selection_claim_id) VALUES ('CAN','Canada','CAN','Montréal / Québec','C16');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S1','CRU','Data centre connection policy consultation','https://www.cru.ie/about-us/news/new-electricity-connection-policy-for-data-centre/','2025-02-18','Ireland','Proposal only; current final-policy status requires follow-up. No site offer.','primary','2026-10-05T20:38:25.425420+00:00','agent_reviewed','implementation agent','2026-10-05T20:38:25.425420+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S2','Fingrid','Southern Finland connection capacity update','https://www.fingrid.fi/en/news/news/2025/fingrid-secures-transmission-capacity-for-growth-in-electricity-consumption-and-new-industrial-investments--restrictions-on-new-energy-storage-facility-connections-continued-in-southern-finland/','2025-09-26','Finland','Storage restrictions are distinct from consumption connections. No site offer.','primary','2026-10-05T20:38:25.425420+00:00','agent_reviewed','implementation agent','2026-10-05T20:38:25.425420+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S3','Hydro-Québec','Proposed large data centre tariff','https://news.hydroquebec.com/news/press-releases/all-quebec/hydro-quebec-proposing-regie-energie-new-rate-large-data-centres-adjustment-rate-cryptographic-use-applied-blockchains.html','2026-02-19','Québec','Proposed CAD tariff; approval and actual connection conditions unverified.','primary','2026-10-05T20:38:25.425420+00:00','agent_reviewed','implementation agent','2026-10-05T20:38:25.425420+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S4','CSO Ireland','Data centres metered electricity consumption 2024','https://www.cso.ie/en/releasesandpublications/ep/p-dcmec/datacentresmeteredelectricityconsumption2024/','2025-06-10','Ireland','Historical national consumption share, not facility count or latest-year assertion.','primary','2026-10-05T20:38:25.425420+00:00','agent_reviewed','implementation agent','2026-10-05T20:38:25.425420+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S5','Statistics Finland','Production of electricity and heat 2024','https://stat.fi/en/statistics/salatuo','2025-11-27','Finland','Annual production; fossil-free includes nuclear and is not renewable-only or hourly supply.','primary','2026-10-05T20:38:25.425420+00:00','agent_reviewed','implementation agent','2026-10-05T20:38:25.425420+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S6','World Bank / IEA','Renewable electricity output (% of total electricity output)','https://data.worldbank.org/indicator/EG.ELC.RNEW.ZS',NULL,'National','Historical national output, not site supply or hourly carbon. CC BY 4.0 World Bank data terms; underlying IEA attribution.','primary','2026-10-05T20:38:25.425420+00:00','agent_api_verified',NULL,'2026-10-05T20:44:15.818995+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S7','Epoch AI','Research inventory','https://epoch.ai',NULL,'Global','Inventory for future demand research; no quantitative forecast taken from this site.','research','2026-10-05T20:38:25.425420+00:00','inventory',NULL,NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S8','NVIDIA','DGX H100 specifications','https://www.nvidia.com/en-us/data-center/dgx-h100/',NULL,'Global','Reference class; 1.4 kW allocated system power and USD acquisition price are planning assumptions, not vendor quotes.','primary','2026-10-05T20:38:25.425420+00:00','inventory',NULL,NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S9','Hydro-Québec','Electricity supply emissions','https://www.hydroquebec.com/sustainable-development/energy-environment/greenhouse-gases.html',NULL,'Québec','Source inventory only; numeric intensity awaits verification.','primary','2026-10-05T20:38:25.425420+00:00','inventory',NULL,NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S10','CRU','Final electricity connection policy for data centres','https://www.cru.ie/about-us/news/the-cru-publishes-its-decision-on-new-electricity-connection-policy-for-data-centres/','2025-12-12','Ireland','Final decision announcement; application-specific capacity, implementing process and site offer remain unverified.','primary','2026-10-05T21:05:08.588471+00:00','agent_reviewed','implementation agent','2026-10-05T21:05:08.588471+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S11','Eurostat','Large non-household electricity prices, 2025-S2','https://ec.europa.eu/eurostat/databrowser/view/nrg_pc_205/default/table?lang=en','2026-10-05','Ireland and Finland','Band IF: 70–150 GWh/year; national supplier averages, not regional offers. Baseline modeled consumption can exceed this band. Different tax categories require adjustment.','primary','2026-10-06T02:12:53.217859+00:00','agent_reviewed','implementation agent','2026-10-06T02:12:53.217859+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S12','Finnish Tax Administration','Data centres move to electricity tax class I in July 2026','https://www.vero.fi/yritykset-ja-yhteisot/verot-ja-maksut/valmisteverotus/sahkovero/',NULL,'Finland','Official Finnish guidance; no preferential data-centre class II assumed after July 2026.','primary','2026-10-06T02:12:53.217859+00:00','agent_reviewed','implementation agent','2026-10-06T02:12:53.217859+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S13','Finnish Tax Administration','Electricity tax table effective April 2026','https://www.vero.fi/yritykset-ja-yhteisot/verot-ja-maksut/valmisteverotus/sahkovero/verotaulukot/','2026-04-01','Finland','Class I energy tax plus security fee; VAT excluded.','primary','2026-10-06T02:12:53.217859+00:00','agent_reviewed','implementation agent','2026-10-06T02:12:53.217859+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S14','Bank of Canada','Annual average exchange rates 2025','https://www.bankofcanada.ca/rates/exchange/annual-average-exchange-rates/','2025-12-31','CAD, EUR, USD','2025 annual averages held constant for screening; not October 2026 spot rates or currency forecasts. Derived EUR/USD cross-rate uses averages.','primary','2026-10-06T02:12:53.217859+00:00','agent_reviewed','implementation agent','2026-10-06T02:12:53.217859+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S15','Nebius','Compute resource prices effective October 1, 2026','https://docs.nebius.com/compute/resources/pricing','2026-10-01','Finland eu-north1','H100 non-preemptible USD4.50/GPU-hour; CPU/RAM included in marketed HGX bundle. Storage and bulk capacity/commitment terms need quotes. Older marketing and introductory prices not used.','primary','2026-10-06T02:12:53.217859+00:00','agent_reviewed','implementation agent','2026-10-06T02:12:53.217859+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S16','Nebius','Public cloud regions','https://docs.nebius.com/overview/regions',NULL,'Finland','eu-north1 is Finland; no allocation or cluster reservation promised.','primary','2026-10-06T02:12:53.217859+00:00','agent_reviewed','implementation agent','2026-10-06T02:12:53.217859+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S17','AWS','Canada Central EC2 public price list, Linux p5.48xlarge','https://pricing.us-east-1.amazonaws.com/offers/v1.0/aws/AmazonEC2/current/ca-central-1/index.csv','2026-09-25','Canada Central','Used/Shared/Linux/NA OnDemand only; USD63.296 per 8-GPU instance-hour. Not zero-price reservation meter, spot, Windows or negotiated quote. No capacity guarantee.','primary','2026-10-06T02:12:53.217859+00:00','agent_reviewed','implementation agent','2026-10-06T02:12:53.217859+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S18','Microsoft Azure','Retail price API: North Europe H100 offers','https://prices.azure.com/api/retail/prices','2024-05-01','Ireland / North Europe','Query and full response saved in research report; Linux NC40ads H100 non-spot price USD8.376/hour, effective May 2024 and still returned now. Price entry is not allocation availability.','primary','2026-10-06T02:12:53.217859+00:00','agent_reviewed','implementation agent','2026-10-06T02:12:53.217859+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S19','Microsoft Azure','NCads H100 v5 hardware specifications','https://learn.microsoft.com/en-us/azure/virtual-machines/sizes/gpu-accelerated/ncadsh100v5-series',NULL,'Azure','Single H100 NVL 94GB differs from H100 SXM80GB/InfiniBand training cluster. One-for-one productive equivalence is an unvalidated model assumption.','primary','2026-10-06T02:12:53.217859+00:00','agent_reviewed','implementation agent','2026-10-06T02:12:53.217859+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S20','Microsoft Azure','Azure region locations','https://learn.microsoft.com/azure/reliability/availability-zones-region-support',NULL,'Ireland','North Europe is Ireland; region location alone does not prove H100 allocation.','primary','2026-10-06T02:12:53.217859+00:00','agent_reviewed','implementation agent','2026-10-06T02:12:53.217859+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S21','Hydro-Québec','Electricity rates effective April 2026','https://www.hydroquebec.com/data/documents-donnees/pdf/electricity-rates.pdf','2026-04-01','Québec','Rate LG CAD16.571/kW/month + CAD0.04324/kWh; monthly peak and minimum billing demand matter. New data-centre tariff proposal may replace this reference.','primary','2026-10-06T02:12:53.217859+00:00','agent_reviewed','implementation agent','2026-10-06T02:12:53.217859+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S22','Régie de l’énergie','Data-centre tariff proceeding R-4333-2026','https://www.regie-energie.qc.ca/fr/participants/dossiers/R-4333-2026','2026-02-19','Québec','Proceeding includes revised proposals through August 2026. Final substantive tariff approval not verified; do not infer it from a procedural decision.','primary','2026-10-06T02:12:53.217859+00:00','agent_reviewed','implementation agent','2026-10-06T02:12:53.217859+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S23','Fingrid','August 2026 grid connection and balancing update','https://www.fingrid.fi/en/news/news/2026/electricity-consumption-is-set-to-increase-sharply--more-balancing-power-will-also-be-needed/','2026-08-18','Finland','New capacity almost fully reserved in many areas; regional waiting continues. Northern opportunities are not a Helsinki/Uusimaa offer.','primary','2026-10-06T02:12:53.217859+00:00','agent_reviewed','implementation agent','2026-10-06T02:12:53.217859+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S24','Irish Data Protection Commission','Cloud processing and controller obligations','https://www.dataprotection.ie/en/faqs/responsibilities-data-controllers/can-i-use-cloud-service-process-my-data',NULL,'Ireland / EEA','Controller/processor agreement and additional safeguards for non-EEA storage; institution-specific assessment remains necessary.','primary','2026-10-06T02:12:53.217859+00:00','agent_reviewed','implementation agent','2026-10-06T02:12:53.217859+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S25','Office of the Privacy Commissioner of Canada','Privacy and outsourcing obligations','https://www.priv.gc.ca/en/privacy-topics/employers-and-employees/outsourcing/02_05_d_57_os_01/',NULL,'Canada','Private-sector PIPEDA guidance; public universities may fall under provincial/public-sector laws. Does not establish a universal Canada-only storage requirement.','primary','2026-10-06T02:12:53.217859+00:00','agent_reviewed','implementation agent','2026-10-06T02:12:53.217859+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S26','OVHcloud','Public cloud advertised H100 PCIe pricing','https://www.ovhcloud.com/en-ca/public-cloud/prices/',NULL,'OVH Canadian storefront','CAD4.05 for h100-380, PCIe single GPU; storefront currency does not establish Québec availability, large-cluster fabric or workload equivalence. Excluded from baseline but retained as a cheaper quote candidate.','primary','2026-10-06T02:12:53.217859+00:00','agent_reviewed','implementation agent','2026-10-06T02:12:53.217859+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S27','AWS','Accelerated computing instance specifications','https://docs.aws.amazon.com/ec2/latest/instancetypes/ac.html',NULL,'AWS','p5.48xlarge has 8 H100 GPUs. Performance equivalence and availability still require workload validation.','primary','2026-10-06T02:12:53.217859+00:00','agent_reviewed','implementation agent','2026-10-06T02:12:53.217859+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S28','JLL','2026 Global Data Center Outlook','https://www.jll.com/content/dam/jllcom/en/global/documents/reports/research-reports/26-research-global-data-center-outlook-new.pdf',NULL,'Global','Page 25: forecast shell/core cost for 50MW air-cooled facility, excludes land and active IT; liquid cooling +10%. Applying global average to 20MW is a planning extrapolation, not a local quote.','primary','2026-10-06T03:08:11.586069+00:00','agent_reviewed','implementation agent','2026-10-06T03:08:11.586069+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S29','Exxact','Eight-GPU HGX H100 server configurator','https://configurator.exxactcorp.com/configure/TS4-193475697',NULL,'US public catalog','Dynamic advertised configurations: Essential 319924, Professional 316184, Premium 333784 USD. Search cache differed from directly opened page; use direct current values. Tax, shipping, imports, bulk supply and shared fabric not priced.','primary','2026-10-06T03:08:11.586069+00:00','agent_reviewed','implementation agent','2026-10-06T03:08:11.586069+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S30','NVIDIA','DGX H100 system datasheet','https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/nvidia-dgx-h100-datasheet.pdf',NULL,'Hardware reference','Eight H100 GPUs and approximately 10.2kW maximum system draw; 1.275kW/GPU is a calculation, not workload productivity.','primary','2026-10-06T03:08:11.586069+00:00','agent_reviewed','implementation agent','2026-10-06T03:08:11.586069+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S31','Research authors / arXiv','Empirical Measurements of AI Training Power Demand on a GPU-Accelerated Node','https://arxiv.org/html/2412.08602v1',NULL,'One tested H100 node','One-node study: idle 1.86kW; maximum measured 8.48kW, rated 10.2kW. Workload/configuration-specific; not a fleet power curve or provider performance comparison.','primary','2026-10-06T03:08:11.586069+00:00','agent_reviewed','implementation agent','2026-10-06T03:08:11.586069+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S32','AWS','EC2 billing by instance state','https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html',NULL,'AWS','Running instances are billed even when idle. Stopped compute is not billed; storage can remain charged. Reserved instances billed through term.','primary','2026-10-06T03:08:11.586069+00:00','agent_reviewed','implementation agent','2026-10-06T03:08:11.586069+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO sources (id,publisher,title,url,publication_date,geographic_scope,limitations,source_type,accessed_at,verification_status,reviewer,verified_at) VALUES ('S33','Microsoft Azure','VM states and billing','https://learn.microsoft.com/en-us/azure/virtual-machines/states-billing',NULL,'Azure','Stopped allocated VM remains billed; deallocated compute is not billed. Other resources continue charges; reallocation availability not promised.','primary','2026-10-06T03:08:11.586069+00:00','agent_reviewed','implementation agent','2026-10-06T03:08:11.586069+00:00');
--> statement-breakpoint
INSERT OR IGNORE INTO designs (id,team_id,selected_country_id,current_revision,it_load_mw,pue,cooling,backup,network,storage,summary,inputs_json,updated_at) VALUES ('baseline','course-consortium',NULL,1,20,1.25,'Closed-loop liquid / dry cooling concept','10-minute UPS; N+1 generation and critical shedding; fuel unknown','Dual diverse carriers / training fabric','Parallel scratch / replicated archive; sizing TBD','No utility offer or committed demand','{"itLoadMw":20,"pue":1.25,"utilization":0.6,"electricityMultiplier":1,"gpuMultiplier":1,"facilityMultiplier":1,"delayMonths":0,"country":"FIN","fixed":{"reference":"NVIDIA H100 SXM 80GB planning-equivalent GPU","systemKwPerGpu":1.4,"nonGpuShare":0.1,"usableFraction":0.95,"idleFraction":0.35,"baselineDemandHours":64197572.4,"facilityPerMw":12430000,"gpuPrice":39990.5,"otherItPerMw":1500000,"gridPerMw":500000,"staffPerMw":180000,"pricingVersion":"research-2026-10-05-costs","leasePerHour":null,"leaseByCountry":{"IRL":8.376,"FIN":4.5,"CAN":7.912},"leaseProductiveFraction":0.95,"leaseSupport":0.1,"leaseCommitmentFraction":0,"tariffs":{"IRL":0.19464993561310634,"FIN":0.07321953784518528,"CAN":0.09300329088567749},"discount":0.08,"debtShare":0.6,"interest":0.06,"tenor":7,"gpuLife":4,"otherItLife":5,"openingMonth":24}}','2026-10-06T03:14:03.180Z');
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C1','baseline',NULL,'No members have signed long-term computing commitments.','fact','[]','active',NULL,NULL,'Assignment starting fact; no signed demand dataset provided.','Assignment starting fact; no signed demand dataset provided.','2026-10-05T20:38:25.425420+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C2','baseline',NULL,'Utility price, required upgrades and energization date are unknown.','unknown','[]','active',NULL,NULL,'Utility offer required before investment approval.','Utility offer required before investment approval.','2026-10-05T20:38:25.425420+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C3','baseline',NULL,'Baseline is 20 MW IT, PUE 1.25 and 25 MW facility load.','assumption','[]','active',NULL,NULL,'Assignment baseline; PUE is not measured.','Assignment baseline; PUE is not measured.','2026-10-05T20:38:25.425420+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C4','baseline',NULL,'Full-load annual energy is 219 GWh: 20 × 1.25 × 8760 / 1000.','calculation','[]','active',NULL,NULL,'Nameplate energy, not modeled operating consumption.','Nameplate energy, not modeled operating consumption.','2026-10-05T20:38:25.425420+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C5','baseline','IRL','CRU published a proposed connection policy in February 2025, including location and generation considerations.','fact','["S1"]','active',NULL,NULL,'Final-policy status remains unresolved; proposal is not enforced-rule proof.','Final-policy status remains unresolved; proposal is not enforced-rule proof.','2026-10-05T20:38:25.425420+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C6','baseline','FIN','Fingrid reported southern connection capacity constraints; storage restrictions extend to 2029, with consumption restrictions previously announced to early 2027.','fact','["S2"]','active',NULL,NULL,'Check latest operator policy and individual site; storage capacity is not datacenter capacity.','Check latest operator policy and individual site; storage capacity is not datacenter capacity.','2026-10-05T20:38:25.425420+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C7','baseline','CAN','Hydro-Québec proposed a new tariff for data centres over 5 MW; projects remain subject to selection.','fact','["S3"]','active',NULL,NULL,'Proposed average CAD 0.13/kWh subject to approval; not used as a confirmed delivered tariff.','Proposed average CAD 0.13/kWh subject to approval; not used as a confirmed delivered tariff.','2026-10-05T20:38:25.425420+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C8','baseline','IRL','Data centres represented 22% of metered electricity consumption in 2024.','fact','["S4"]','active',NULL,NULL,'Historical national ecosystem measure; not comparable to a facility count.','Historical national ecosystem measure; not comparable to a facility count.','2026-10-05T20:38:25.425420+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C9','baseline','FIN','Statistics Finland reports 95% fossil-free electricity production in 2024.','fact','["S5"]','active',NULL,NULL,'Annual domestic production; includes nuclear. No 24/7 matching claim.','Annual domestic production; includes nuclear. No 24/7 matching claim.','2026-10-05T20:38:25.425420+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C10','baseline',NULL,'Demand forecast is 64,197,572.4 productive H100-equivalent GPU-hours per year.','assumption','[]','active',NULL,NULL,'Derived once from baseline capacity: floor(18000/1.4) × 0.95 × 8760 × 0.60. Fixed across scale scenarios; uncommitted.','Derived once from baseline capacity: floor(18000/1.4) × 0.95 × 8760 × 0.60. Fixed across scale scenarios; uncommitted.','2026-10-05T20:38:25.425420+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C11','baseline',NULL,'Costs are illustrative: facility USD 8m/MW; GPU USD 30k; lease USD 3/productive hour; delivered power IRL .15, FIN .10, CAN .10 USD/kWh.','assumption','[]','active',NULL,NULL,'Constant 2026 USD; no utility/vendor quote or FX claim. These identical Canada/Finland values are assumptions, not country rankings.','Constant 2026 USD; no utility/vendor quote or FX claim. These identical Canada/Finland values are assumptions, not country rankings.','2026-10-05T20:38:25.425420+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C12','baseline',NULL,'Hybrid owns 50% initially and expands at start of year 4, subject to grid availability.','design_decision','[]','active',NULL,NULL,'Fixed comparison schedule, not optimized.','Fixed comparison schedule, not optimized.','2026-10-05T20:38:25.425420+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C13','baseline',NULL,'Reserve 20% of allocation for smaller institutions; teaching reservations, research quotas and overflow are proposed.','design_decision','[]','active',NULL,NULL,'No consortium agreement; independent board resolves conflicts and admits members.','No consortium agreement; independent board resolves conflicts and admits members.','2026-10-05T20:38:25.425420+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C14','baseline','IRL','Indicative research region: greater Dublin, chosen to investigate ecosystem and constrained-grid tradeoffs.','design_decision','["S1", "S4"]','active',NULL,NULL,'No parcel selected; permits and utility offer unknown.','No parcel selected; permits and utility offer unknown.','2026-10-05T20:38:25.425420+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C15','baseline','FIN','Indicative research region: Helsinki/Uusimaa, chosen to investigate connectivity against southern-grid constraints.','design_decision','["S2"]','active',NULL,NULL,'No claim of unconstrained capacity.','No claim of unconstrained capacity.','2026-10-05T20:38:25.425420+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C16','baseline','CAN','Indicative research region: Montréal/Québec, chosen to investigate provincial allocation and tariff conditions.','design_decision','["S3"]','active',NULL,NULL,'Provincial evidence must not be generalized to Canada.','Provincial evidence must not be generalized to Canada.','2026-10-05T20:38:25.425420+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C17','baseline',NULL,'Operating power uses 35% idle fraction, with 95% usable hours and 60% productive utilization.','assumption','[]','active',NULL,NULL,'Coarse power curve, not telemetry; usable fraction applied once.','Coarse power curve, not telemetry; usable fraction applied once.','2026-10-05T20:38:25.425420+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C18','baseline',NULL,'Equivalent leased throughput, egress, reservation guarantees and security remain unverified.','unknown','[]','active',NULL,NULL,'Uniform H100 GPU-hour pricing does not prove workload equivalence.','Uniform H100 GPU-hour pricing does not prove workload equivalence.','2026-10-05T20:38:25.425420+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C19','baseline',NULL,'No uptime guarantee: 48-hour critical operation requires fuel, cooling and network validation.','unknown','[]','active',NULL,NULL,'UPS ride-through alone does not establish 48-hour availability.','UPS ride-through alone does not establish 48-hour availability.','2026-10-05T20:38:25.425420+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C20','baseline','IRL','CRU announced its final connection policy on 12 December 2025. New connections require local or onsite generation/storage matching maximum import demand, plus at least 80% annual demand from additional renewable projects in Ireland with a six-year glide path.','fact','["S10"]','active',NULL,NULL,'Final announcement supersedes the February consultation status. These are policy conditions, not an approved project or capacity offer.','Location constraints, implementing process and a project-specific connection offer remain unverified.','2026-10-05T21:05:08.588471+00:00','C5');
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C21','baseline',NULL,'Replace identical price placeholders with researched country/provider benchmarks and explicit conversions.','assumption','["S11", "S12", "S13", "S14", "S15", "S17", "S18"]','active',NULL,NULL,'Public GPU prices normalized to USD per billed GPU-hour; model uses 95% productive fraction plus 10% service allowance. Remaining ownership costs stay illustrative.','Different suppliers and hardware mean this is screening, not an executable procurement comparison.','2026-10-06T02:12:53.217859+00:00','C11');
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C22','baseline','IRL','Electricity input: 0.17240 EUR/kWh = 0.194650 USD/kWh; 2025-S2 Eurostat band IF, excluding VAT/recoverable taxes.','assumption','["S11", "S14"]','active',NULL,NULL,'2025 BoC FX cross-rate held constant; no 2026 inflation escalation. Band IF may not match modeled consumption at every scale.','National electricity proxy; H100 NVL94GB single GPU is not validated as SXM80GB/InfiniBand-equivalent. Storage/egress and cluster allocation unknown.','2026-10-06T02:12:53.217859+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C23','baseline','FIN','Electricity input: 0.06485 EUR/kWh = 0.073220 USD/kWh; 2025-S2 Eurostat band IF ex-tax energy/network + 2026 class I tax/fee.','assumption','["S11", "S12", "S13", "S14"]','active',NULL,NULL,'2025 BoC FX cross-rate held constant; no 2026 inflation escalation. Band IF may not match modeled consumption at every scale.','National proxy with current data-centre tax adjustment, not a Uusimaa utility offer. Storage, quota and reservation terms unknown.','2026-10-06T02:12:53.217859+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C24','baseline','CAN','Electricity input: 0.13000 CAD/kWh = 0.093003 USD/kWh; Hydro-Québec proposed average new >5MW data-centre rate; planning policy scenario.','assumption','["S3", "S14", "S21", "S22"]','active',NULL,NULL,'2025 BoC FX cross-rate held constant; no 2026 inflation escalation. Band IF may not match modeled consumption at every scale.','Proposed electricity rate not confirmed approved; LG demand-billed fallback shown separately. AWS regional public on-demand benchmark, not cheapest Canadian supplier or capacity offer.','2026-10-06T02:12:53.217859+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C25','baseline','IRL','Published rental benchmark: Azure North Europe NC40ads H100 v5 at USD 8.376 per allocated GPU-hour.','fact','["S18", "S19", "S20"]','active',NULL,NULL,'Non-spot/non-preemptible public price; per-GPU division where instance contains eight GPUs. Running-hour price is not productive-hour price.','National electricity proxy; H100 NVL94GB single GPU is not validated as SXM80GB/InfiniBand-equivalent. Storage/egress and cluster allocation unknown.','2026-10-06T02:12:53.217859+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C26','baseline','FIN','Published rental benchmark: Nebius eu-north1 H100 NVLink at USD 4.500 per allocated GPU-hour.','fact','["S15", "S16"]','active',NULL,NULL,'Non-spot/non-preemptible public price; per-GPU division where instance contains eight GPUs. Running-hour price is not productive-hour price.','National proxy with current data-centre tax adjustment, not a Uusimaa utility offer. Storage, quota and reservation terms unknown.','2026-10-06T02:12:53.217859+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C27','baseline','CAN','Published rental benchmark: AWS Canada Central p5.48xlarge, 8 H100 GPUs at USD 7.912 per allocated GPU-hour.','fact','["S17", "S27"]','active',NULL,NULL,'Non-spot/non-preemptible public price; per-GPU division where instance contains eight GPUs. Running-hour price is not productive-hour price.','Proposed electricity rate not confirmed approved; LG demand-billed fallback shown separately. AWS regional public on-demand benchmark, not cheapest Canadian supplier or capacity offer.','2026-10-06T02:12:53.217859+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C28','baseline','FIN','Data-centre electricity moves to class I from July 1, 2026; class I tax and security fee total 2.325 euro cents/kWh under the April 2026 table.','fact','["S12", "S13"]','active',NULL,NULL,'Use ex-tax historical energy/network proxy plus current class I charges to avoid double-counting taxes.','Future charges and utility supply price can change.','2026-10-06T02:12:53.217859+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C29','baseline','FIN','August 2026 Fingrid update warns that additional connection capacity is almost fully reserved in many areas and regional waiting times continue.','fact','["S23"]','active',NULL,NULL,'Updates the earlier 2025 southern-grid context; does not promise access in 2027.','Site-specific utility diligence remains necessary.','2026-10-06T02:12:53.217859+00:00','C6');
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C30','baseline','CAN','Rate LG currently lists CAD16.571/kW/month plus CAD0.04324/kWh; new large data-centre tariff proposal is a distinct policy scenario.','fact','["S21", "S22", "S3"]','active',NULL,NULL,'At assumed 74% load factor, flat full-peak billing gives ~CAD0.073915/kWh before credits/taxes; this calculation is a reference, not an offer.','Peak/minimum demand and tariff eligibility can materially change the bill.','2026-10-06T02:12:53.217859+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C31','baseline','IRL','Cloud controllers must assess processor guarantees, use a written agreement and establish data handling locations; non-EEA storage needs additional safeguards.','fact','["S24"]','active',NULL,NULL,'Apply to Irish member workload screening; avoid inferring an unrestricted cross-border consortium.','Specific institutional policies and sensitive-data categories unknown.','2026-10-06T02:12:53.217859+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C32','baseline','CAN','Canadian outsourcing privacy duties depend on the applicable legal regime; public-university provincial obligations need assessment.','unknown','["S25"]','active',NULL,NULL,'Federal private-sector PIPEDA guidance is not a universal university rule.','Member institutions, data categories and provincial/public-sector requirements not supplied.','2026-10-06T02:12:53.217859+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C33','baseline',NULL,'Provider region and interconnect specifications are known; end-to-end member latency and workload equivalence remain unmeasured.','unknown','["S16", "S19", "S20", "S27"]','active',NULL,NULL,'Do not invent millisecond latency or a benchmark proving NVL/PCIe/SXM equivalence.','Validate representative multi-node training and teaching/inference workloads before contracts.','2026-10-06T02:12:53.217859+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C34','baseline','CAN','OVHcloud advertises CAD4.05/hour for a single H100 PCIe h100-380; Québec location and training-cluster equivalence are not established by the Canadian storefront.','fact','["S26"]','active',NULL,NULL,'Retained as a lower-price procurement research candidate, not silently substituted for an 8-GPU H100 cluster benchmark.','Could reverse country/strategy preference if suitable capacity and performance are proven.','2026-10-06T02:12:53.217859+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C35','baseline',NULL,'Facility construction basis is USD12.43 million per MW IT: global 2026 shell/core forecast USD11.3m/MW plus 10% liquid-cooling premium.','calculation','["S28"]','active',NULL,NULL,'Global proxy held equal across countries; analyst sensitivity ±20%. This range is a planning stress, not a published uncertainty interval.','Scale, land, local supply chains and site-specific grid work remain unpriced.','2026-10-06T03:08:11.586069+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C36','baseline',NULL,'Owned GPU-server cost is USD39,990.50 per GPU-equivalent: advertised eight-H100 server USD319,924 divided by eight.','calculation','["S29"]','active',NULL,NULL,'Includes server CPU/RAM/baseboard; USD1.5m/MW separate allowance covers shared fabric/storage, excluding bundled host components. Model allocates cost per GPU, not an order for fractional servers.','Observed configuration range USD39,523–41,723/GPU; import/tax/shipping/discounts and future replacement prices unknown.','2026-10-06T03:08:11.586069+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C37','baseline',NULL,'NVIDIA DGX H100 rated maximum 10.2kW across eight GPUs implies 1.275kW per GPU including node overhead.','calculation','["S30"]','active',NULL,NULL,'Retain conservative 1.4kW planning allocation; compare 1.275kW in robustness analysis with demand unchanged.','DGX is a reference, not the Exxact server or leased performance guarantee.','2026-10-06T03:08:11.586069+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C38','baseline',NULL,'An empirical eight-H100 node study reports 1.86kW idle and 8.48kW maximum measured power.','fact','["S31"]','active',NULL,NULL,'Idle/rated ratio approximately 18.2%; compare it with 35% planning idle fraction rather than treat one node as fleet telemetry.','Power is not productive throughput; a multi-node workload benchmark remains missing.','2026-10-06T03:08:11.586069+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C39','baseline',NULL,'Compute billing follows allocated/running resources, not useful GPU work; stopped/deallocated treatment differs by provider.','fact','["S15", "S32", "S33"]','active',NULL,NULL,'Pay-as-you-go savings require actually releasing compute; storage can remain billed and reserved commitments differ.','Restart capacity, productive throughput, storage/egress costs and reservations need workload and contract evidence.','2026-10-06T03:08:11.586069+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_claims (id,design_id,country_id,text,type,source_ids,status,value,unit,rationale,uncertainty,updated_at,supersedes_id) VALUES ('C40','baseline',NULL,'Robustness tests vary ownership cost, productive conversion, idle power, refresh life and retained rental allocation.','assumption','["S28", "S29", "S30", "S31", "S32", "S33"]','active',NULL,NULL,'Published benchmarks anchor costs. ±20% construction, 70–100% productive conversion and retained-allocation billing are explicit analyst scenarios, not empirical distributions.','No scenario probability or confidence percentage is inferred; an unchanged winner across tested cases is not investment approval.','2026-10-06T03:08:11.586069+00:00',NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO metrics (id,country_id,metric_name,value,unit,period,source_id,retrieved_at,limitation,definition,geographic_scope,refresh_run_id,supersedes_id) VALUES ('WB-IRL-2021','IRL','renewable_output_share',37.1541775946047,'%','2021','S6','2026-10-05T20:44:15.818995+00:00','Historical 2021 national annual output, not site supply, current mix or hourly carbon. Latest available non-null year in verified response.','Renewable electricity output as share of total electricity output','IRL',NULL,NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO metrics (id,country_id,metric_name,value,unit,period,source_id,retrieved_at,limitation,definition,geographic_scope,refresh_run_id,supersedes_id) VALUES ('WB-FIN-2021','FIN','renewable_output_share',52.9302986606029,'%','2021','S6','2026-10-05T20:44:15.818995+00:00','Historical 2021 national annual output, not site supply, current mix or hourly carbon. Latest available non-null year in verified response.','Renewable electricity output as share of total electricity output','FIN',NULL,NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO metrics (id,country_id,metric_name,value,unit,period,source_id,retrieved_at,limitation,definition,geographic_scope,refresh_run_id,supersedes_id) VALUES ('WB-CAN-2021','CAN','renewable_output_share',67.0163805768966,'%','2021','S6','2026-10-05T20:44:15.818995+00:00','Historical 2021 national annual output, not site supply, current mix or hourly carbon. Latest available non-null year in verified response.','Renewable electricity output as share of total electricity output','CAN',NULL,NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO metrics (id,country_id,metric_name,value,unit,period,source_id,retrieved_at,limitation,definition,geographic_scope,refresh_run_id,supersedes_id) VALUES ('RESEARCH-IRL-screening_electricity_usd_kwh-20261005','IRL','screening_electricity_usd_kwh',0.19464993561310634,'USD/kWh','2025-S2 / 2026 policy','S11','2026-10-06T02:12:53.217859+00:00','National electricity proxy; H100 NVL94GB single GPU is not validated as SXM80GB/InfiniBand-equivalent. Storage/egress and cluster allocation unknown.','Calculated USD electricity planning input, including selected tax/policy treatment','IRL',NULL,NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO metrics (id,country_id,metric_name,value,unit,period,source_id,retrieved_at,limitation,definition,geographic_scope,refresh_run_id,supersedes_id) VALUES ('RESEARCH-IRL-published_allocated_gpu_hour_usd-20261005','IRL','published_allocated_gpu_hour_usd',8.376,'USD/GPU-hour','2026-10-05 retrieval','S18','2026-10-06T02:12:53.217859+00:00','National electricity proxy; H100 NVL94GB single GPU is not validated as SXM80GB/InfiniBand-equivalent. Storage/egress and cluster allocation unknown.','Published non-spot rental benchmark per allocated GPU-hour, not productive GPU-hour','IRL',NULL,NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO metrics (id,country_id,metric_name,value,unit,period,source_id,retrieved_at,limitation,definition,geographic_scope,refresh_run_id,supersedes_id) VALUES ('RESEARCH-FIN-screening_electricity_usd_kwh-20261005','FIN','screening_electricity_usd_kwh',0.07321953784518528,'USD/kWh','2025-S2 / 2026 policy','S11','2026-10-06T02:12:53.217859+00:00','National proxy with current data-centre tax adjustment, not a Uusimaa utility offer. Storage, quota and reservation terms unknown.','Calculated USD electricity planning input, including selected tax/policy treatment','FIN',NULL,NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO metrics (id,country_id,metric_name,value,unit,period,source_id,retrieved_at,limitation,definition,geographic_scope,refresh_run_id,supersedes_id) VALUES ('RESEARCH-FIN-published_allocated_gpu_hour_usd-20261005','FIN','published_allocated_gpu_hour_usd',4.5,'USD/GPU-hour','2026-10-05 retrieval','S15','2026-10-06T02:12:53.217859+00:00','National proxy with current data-centre tax adjustment, not a Uusimaa utility offer. Storage, quota and reservation terms unknown.','Published non-spot rental benchmark per allocated GPU-hour, not productive GPU-hour','FIN',NULL,NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO metrics (id,country_id,metric_name,value,unit,period,source_id,retrieved_at,limitation,definition,geographic_scope,refresh_run_id,supersedes_id) VALUES ('RESEARCH-CAN-screening_electricity_usd_kwh-20261005','CAN','screening_electricity_usd_kwh',0.09300329088567749,'USD/kWh','2025-S2 / 2026 policy','S3','2026-10-06T02:12:53.217859+00:00','Proposed electricity rate not confirmed approved; LG demand-billed fallback shown separately. AWS regional public on-demand benchmark, not cheapest Canadian supplier or capacity offer.','Calculated USD electricity planning input, including selected tax/policy treatment','CAN',NULL,NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO metrics (id,country_id,metric_name,value,unit,period,source_id,retrieved_at,limitation,definition,geographic_scope,refresh_run_id,supersedes_id) VALUES ('RESEARCH-CAN-published_allocated_gpu_hour_usd-20261005','CAN','published_allocated_gpu_hour_usd',7.912,'USD/GPU-hour','2026-10-05 retrieval','S17','2026-10-06T02:12:53.217859+00:00','Proposed electricity rate not confirmed approved; LG demand-billed fallback shown separately. AWS regional public on-demand benchmark, not cheapest Canadian supplier or capacity offer.','Published non-spot rental benchmark per allocated GPU-hour, not productive GPU-hour','CAN',NULL,NULL);
--> statement-breakpoint
INSERT OR IGNORE INTO design_revisions (id,design_id,revision,inputs_json,evidence_snapshot,reason,actor_id,created_at) SELECT 'baseline:1',id,1,inputs_json,'{"claim_ids":["C1","C2","C3","C4","C5","C6","C7","C8","C9","C10","C11","C12","C13","C14","C15","C16","C17","C18","C19","C20","C21","C22","C23","C24","C25","C26","C27","C28","C29","C30","C31","C32","C33","C34","C35","C36","C37","C38","C39","C40"],"metric_ids":["WB-IRL-2021","WB-FIN-2021","WB-CAN-2021","RESEARCH-IRL-screening_electricity_usd_kwh-20261005","RESEARCH-IRL-published_allocated_gpu_hour_usd-20261005","RESEARCH-FIN-screening_electricity_usd_kwh-20261005","RESEARCH-FIN-published_allocated_gpu_hour_usd-20261005","RESEARCH-CAN-screening_electricity_usd_kwh-20261005","RESEARCH-CAN-published_allocated_gpu_hour_usd-20261005"]}','Initial researched baseline',NULL,'2026-10-06T03:14:03.180Z' FROM designs WHERE id='baseline' AND current_revision=1;
--> statement-breakpoint
INSERT INTO design_revisions (id,design_id,revision,inputs_json,evidence_snapshot,reason,actor_id,created_at) SELECT 'baseline:'||(current_revision+1),id,current_revision+1,json_set(inputs_json,'$.fixed',json('{"reference":"NVIDIA H100 SXM 80GB planning-equivalent GPU","systemKwPerGpu":1.4,"nonGpuShare":0.1,"usableFraction":0.95,"idleFraction":0.35,"baselineDemandHours":64197572.4,"facilityPerMw":12430000,"gpuPrice":39990.5,"otherItPerMw":1500000,"gridPerMw":500000,"staffPerMw":180000,"pricingVersion":"research-2026-10-05-costs","leasePerHour":null,"leaseByCountry":{"IRL":8.376,"FIN":4.5,"CAN":7.912},"leaseProductiveFraction":0.95,"leaseSupport":0.1,"leaseCommitmentFraction":0,"tariffs":{"IRL":0.19464993561310634,"FIN":0.07321953784518528,"CAN":0.09300329088567749},"discount":0.08,"debtShare":0.6,"interest":0.06,"tenor":7,"gpuLife":4,"otherItLife":5,"openingMonth":24}')),'{"claim_ids":["C1","C2","C3","C4","C5","C6","C7","C8","C9","C10","C11","C12","C13","C14","C15","C16","C17","C18","C19","C20","C21","C22","C23","C24","C25","C26","C27","C28","C29","C30","C31","C32","C33","C34","C35","C36","C37","C38","C39","C40"],"metric_ids":["WB-IRL-2021","WB-FIN-2021","WB-CAN-2021","RESEARCH-IRL-screening_electricity_usd_kwh-20261005","RESEARCH-IRL-published_allocated_gpu_hour_usd-20261005","RESEARCH-FIN-screening_electricity_usd_kwh-20261005","RESEARCH-FIN-published_allocated_gpu_hour_usd-20261005","RESEARCH-CAN-screening_electricity_usd_kwh-20261005","RESEARCH-CAN-published_allocated_gpu_hour_usd-20261005"]}','Researched ownership benchmarks and robustness diagnostics; controls preserved',NULL,'2026-10-06T03:14:03.180Z' FROM designs WHERE id='baseline' AND COALESCE(json_extract(inputs_json,'$.fixed.pricingVersion'),'')<>'research-2026-10-05-costs';
--> statement-breakpoint
UPDATE designs SET inputs_json=json_set(inputs_json,'$.fixed',json('{"reference":"NVIDIA H100 SXM 80GB planning-equivalent GPU","systemKwPerGpu":1.4,"nonGpuShare":0.1,"usableFraction":0.95,"idleFraction":0.35,"baselineDemandHours":64197572.4,"facilityPerMw":12430000,"gpuPrice":39990.5,"otherItPerMw":1500000,"gridPerMw":500000,"staffPerMw":180000,"pricingVersion":"research-2026-10-05-costs","leasePerHour":null,"leaseByCountry":{"IRL":8.376,"FIN":4.5,"CAN":7.912},"leaseProductiveFraction":0.95,"leaseSupport":0.1,"leaseCommitmentFraction":0,"tariffs":{"IRL":0.19464993561310634,"FIN":0.07321953784518528,"CAN":0.09300329088567749},"discount":0.08,"debtShare":0.6,"interest":0.06,"tenor":7,"gpuLife":4,"otherItLife":5,"openingMonth":24}')),current_revision=current_revision+1,updated_at='2026-10-06T03:14:03.180Z' WHERE id='baseline' AND COALESCE(json_extract(inputs_json,'$.fixed.pricingVersion'),'')<>'research-2026-10-05-costs';
--> statement-breakpoint
INSERT OR IGNORE INTO audit_events (id,timestamp,request_id,event_type,actor_id,team_id,entity_id,metadata,outcome) VALUES ('ownership-research-20261005','2026-10-06T03:14:03.180Z','ownership-research-20261005','research_inventory_migrated',NULL,'course-consortium','baseline','{"pricing_version":"research-2026-10-05-costs","source_ids":["S28","S29","S30","S31","S32","S33"],"claim_ids":["C35","C36","C37","C38","C39","C40"],"origin":"reviewed data migration"}','success');
