import test from 'node:test';import assert from 'node:assert/strict';import {energy,evaluate,normalize,rank,sensitivity,FIXED} from '../lib/shared/model.ts';
test('assignment exact nameplate energy and revised PUE',()=>{assert.deepEqual(energy(20,1.25),{facilityMw:25,annualGwh:219});assert.deepEqual(energy(20,1.4),{facilityMw:28,annualGwh:245.28})});
test('reject invalid values and bounded steps',()=>{for(const x of [{pue:NaN},{pue:Infinity},{itLoadMw:0},{pue:1.23},{delayMonths:7},{country:'US'}])assert.throws(()=>normalize(x))});
test('all alternatives deliver same fixed demand at small and large scale',()=>{for(const mw of [5,20,30]){const x=evaluate({itLoadMw:mw});for(const a of x.alternatives){assert.equal(a.unmetHours,0);assert.ok(Math.abs(a.productiveHours-FIXED.baselineDemandHours*10)<1);assert.ok(Math.abs(a.ownedHours+a.leasedHours-a.productiveHours)<1)}}});
test('delay moves owned commissioning, preserves demand and adds bridge/carrying',()=>{const b=evaluate(),d=evaluate({},'delay');assert.equal(d.openingYear,b.openingYear+1);for(let i=0;i<3;i++){assert.equal(d.alternatives[i].productiveHours,b.alternatives[i].productiveHours);if(i!==1){assert.ok(d.alternatives[i].leasedHours>b.alternatives[i].leasedHours);assert.ok(d.alternatives[i].cashBeforeOpening>b.alternatives[i].cashBeforeOpening)}}});
test('half demand preserves capital/fleet/staff and does not halve energy',()=>{const b=evaluate(),h=evaluate({},'half');for(let i of [0,2]){assert.equal(h.alternatives[i].capitalAtRisk,b.alternatives[i].capitalAtRisk);assert.equal(h.alternatives[i].rows[5].staffing,b.alternatives[i].rows[5].staffing);assert.ok(h.alternatives[i].energyKwh>b.alternatives[i].energyKwh*.5);assert.equal(h.alternatives[i].productiveHours,b.alternatives[i].productiveHours*.5)}});
test('tranche replacements follow age; year-4 expansion no duplicate fleet',()=>{const h=evaluate().alternatives[2];assert.ok(h.rows[3].gpus>0);assert.equal(h.rows[3].replacement,0);assert.ok(h.rows[6].replacement>0);assert.ok(h.rows[7].replacement>0)});
test('financing principal and unused allocation not double-counted',()=>{for(const a of evaluate().alternatives)for(const r of a.rows){assert.equal(r.total,r.facility+r.grid+r.gpus+r.otherIt+r.replacement+r.operating+r.interest);assert.ok(r.outstanding>=0);assert.ok(r.unusedAllocation>=0)}});
test('zero demand gives unavailable unit metrics',()=>{for(const a of evaluate({},'base',{...FIXED,baselineDemandHours:0}).alternatives){assert.equal(a.costPerHour,null);assert.equal(a.levelized,null)}});
test('approval gaps do not suppress conditional screening; exact ties stay unresolved',()=>{assert.equal(evaluate().recommendation.verdict,'LEASE');assert.equal(evaluate().recommendation.approval.status,'MORE EVIDENCE REQUIRED');assert.equal(rank([{strategy:'BUILD',discounted:1},{strategy:'LEASE',discounted:1}],[]).verdict,'INSUFFICIENT EVIDENCE');assert.equal(rank([{strategy:'BUILD',discounted:2},{strategy:'LEASE',discounted:1}],[]).verdict,'LEASE')});
test('deterministic reproducibility and complete sensitivity sweep',()=>{assert.deepEqual(evaluate(),evaluate());assert.equal(sensitivity({}).length,7);assert.ok(sensitivity({}).some(x=>x.reversals.length));assert.ok(sensitivity({}).every(x=>x.points.every(p=>['BUILD','LEASE','HYBRID','INSUFFICIENT EVIDENCE'].includes(p.verdict))))});

test('required cases derive preference from costs with approval separately gated',()=>{for(const name of ['base','delay','half']){const r=evaluate({},name);const sorted=[...r.alternatives].sort((a,b)=>a.discounted-b.discounted);assert.equal(r.recommendation.verdict,sorted[0].strategy);assert.equal(r.recommendation.runnerUp,sorted[1].strategy);assert.equal(r.recommendation.savingsVsRunnerUp,sorted[1].discounted-sorted[0].discounted);assert.equal(r.recommendation.approval.gaps.length,3);assert.equal(r.recommendation.conditional,true);}});
test('bounded GPU acquisition scenario changes preference without granting approval',()=>{const base=evaluate(),cheap=evaluate({gpuMultiplier:.75});assert.equal(base.recommendation.verdict,'LEASE');assert.equal(cheap.recommendation.verdict,'HYBRID');assert.equal(cheap.recommendation.approval.status,'MORE EVIDENCE REQUIRED');const sweep=sensitivity({}).find(x=>x.input==='gpuMultiplier');assert.ok(sweep.reversals.some(r=>r.from==='HYBRID'&&r.to==='LEASE'));});
test('invalid costs, zero demand, missing delivery and unequal workload remain unresolved',()=>{assert.equal(rank([{strategy:'BUILD',discounted:NaN}]).verdict,'INSUFFICIENT EVIDENCE');assert.equal(rank([{strategy:'BUILD',discounted:1,unmetHours:10}]).verdict,'INSUFFICIENT EVIDENCE');assert.equal(rank([{strategy:'BUILD',discounted:1,productiveHours:10},{strategy:'LEASE',discounted:2,productiveHours:20}]).verdict,'INSUFFICIENT EVIDENCE');assert.equal(evaluate({},'base',{...FIXED,baselineDemandHours:0}).recommendation.verdict,'INSUFFICIENT EVIDENCE');});
test('overall screening covers nine equivalent workload alternatives without inventing a country winner',async()=>{const {overallScreening}=await import('../lib/shared/model.ts');const x=overallScreening();assert.equal(x.strategy,'LEASE');assert.equal(x.countryStatus,'UNRESOLVED');assert.equal(x.stressConsistent,true);assert.deepEqual(x.rows.map(r=>r.country),['IRL','FIN','CAN']);for(const r of x.rows)for(const k of ['base','delay','half'])assert.equal(r.cases[k].alternatives.length,3);assert.equal(overallScreening({gpuMultiplier:.75}).strategy,'HYBRID');});
