import test from 'node:test';import assert from 'node:assert/strict';import {energy,evaluate,normalize,rank,sensitivity,FIXED,COST_EVIDENCE} from '../lib/shared/model.ts';
test('assignment exact nameplate energy and revised PUE',()=>{assert.deepEqual(energy(20,1.25),{facilityMw:25,annualGwh:219});assert.deepEqual(energy(20,1.4),{facilityMw:28,annualGwh:245.28})});
test('reject invalid values and bounded steps',()=>{for(const x of [{pue:NaN},{pue:Infinity},{itLoadMw:0},{pue:1.23},{delayMonths:7},{country:'US'}])assert.throws(()=>normalize(x))});
test('all alternatives deliver same fixed demand at small and large scale',()=>{for(const mw of [5,20,30]){const x=evaluate({itLoadMw:mw});for(const a of x.alternatives){assert.equal(a.unmetHours,0);assert.ok(Math.abs(a.productiveHours-FIXED.baselineDemandHours*10)<1);assert.ok(Math.abs(a.ownedHours+a.leasedHours-a.productiveHours)<1)}}});
test('delay moves owned commissioning, preserves demand and adds bridge/carrying',()=>{const b=evaluate(),d=evaluate({},'delay');assert.equal(d.openingYear,b.openingYear+1);for(let i=0;i<3;i++){assert.equal(d.alternatives[i].productiveHours,b.alternatives[i].productiveHours);if(i!==1){assert.ok(d.alternatives[i].leasedHours>b.alternatives[i].leasedHours);assert.ok(d.alternatives[i].cashBeforeOpening>b.alternatives[i].cashBeforeOpening)}}});
test('half demand preserves capital/fleet/staff and does not halve energy',()=>{const b=evaluate(),h=evaluate({},'half');for(let i of [0,2]){assert.equal(h.alternatives[i].capitalAtRisk,b.alternatives[i].capitalAtRisk);assert.equal(h.alternatives[i].rows[5].staffing,b.alternatives[i].rows[5].staffing);assert.ok(h.alternatives[i].energyKwh>b.alternatives[i].energyKwh*.5);assert.equal(h.alternatives[i].productiveHours,b.alternatives[i].productiveHours*.5)}});
test('tranche replacements follow age; year-4 expansion no duplicate fleet',()=>{const h=evaluate().alternatives[2];assert.ok(h.rows[3].gpus>0);assert.equal(h.rows[3].replacement,0);assert.ok(h.rows[6].replacement>0);assert.ok(h.rows[7].replacement>0)});
test('financing principal and unused allocation not double-counted',()=>{for(const a of evaluate().alternatives)for(const r of a.rows){assert.equal(r.total,r.facility+r.grid+r.gpus+r.otherIt+r.replacement+r.operating+r.interest);assert.ok(r.outstanding>=0);assert.ok(r.unusedAllocation>=0)}});
test('zero demand gives unavailable unit metrics',()=>{for(const a of evaluate({},'base',{...FIXED,baselineDemandHours:0}).alternatives){assert.equal(a.costPerHour,null);assert.equal(a.levelized,null)}});
test('approval gaps do not suppress conditional screening; exact ties stay unresolved',()=>{assert.equal(evaluate().recommendation.verdict,'HYBRID');assert.equal(evaluate().recommendation.approval.status,'MORE EVIDENCE REQUIRED');assert.equal(rank([{strategy:'BUILD',discounted:1},{strategy:'LEASE',discounted:1}],[]).verdict,'INSUFFICIENT EVIDENCE');assert.equal(rank([{strategy:'BUILD',discounted:2},{strategy:'LEASE',discounted:1}],[]).verdict,'LEASE')});
test('deterministic reproducibility and complete sensitivity sweep',()=>{assert.deepEqual(evaluate(),evaluate());assert.equal(sensitivity({}).length,7);assert.ok(sensitivity({}).some(x=>x.reversals.length));assert.ok(sensitivity({}).every(x=>x.points.every(p=>['BUILD','LEASE','HYBRID','INSUFFICIENT EVIDENCE'].includes(p.verdict))))});

test('required cases derive preference from costs with approval separately gated',()=>{for(const name of ['base','delay','half']){const r=evaluate({},name);const sorted=[...r.alternatives].sort((a,b)=>a.discounted-b.discounted);assert.equal(r.recommendation.verdict,sorted[0].strategy);assert.equal(r.recommendation.runnerUp,sorted[1].strategy);assert.equal(r.recommendation.savingsVsRunnerUp,sorted[1].discounted-sorted[0].discounted);assert.equal(r.recommendation.approval.gaps.length,3);assert.equal(r.recommendation.conditional,true);}});
test('bounded GPU cost scenario changes cost margin without granting approval',()=>{const base=evaluate(),cheap=evaluate({gpuMultiplier:.75});assert.equal(base.recommendation.verdict,'HYBRID');assert.ok(cheap.recommendation.savingsVsRunnerUp!==base.recommendation.savingsVsRunnerUp);assert.equal(cheap.recommendation.approval.status,'MORE EVIDENCE REQUIRED');assert.ok(sensitivity({}).some(x=>x.reversals.length));});
test('invalid costs, zero demand, missing delivery and unequal workload remain unresolved',()=>{assert.equal(rank([{strategy:'BUILD',discounted:NaN}]).verdict,'INSUFFICIENT EVIDENCE');assert.equal(rank([{strategy:'BUILD',discounted:1,unmetHours:10}]).verdict,'INSUFFICIENT EVIDENCE');assert.equal(rank([{strategy:'BUILD',discounted:1,productiveHours:10},{strategy:'LEASE',discounted:2,productiveHours:20}]).verdict,'INSUFFICIENT EVIDENCE');assert.equal(evaluate({},'base',{...FIXED,baselineDemandHours:0}).recommendation.verdict,'INSUFFICIENT EVIDENCE');});
test('overall screening covers nine alternatives and remains conditional across stress',async()=>{const {overallScreening}=await import('../lib/shared/model.ts');const x=overallScreening();assert.equal(x.strategy,'HYBRID');assert.equal(x.countryPreference,'FIN');assert.equal(x.countryStatus,'CONDITIONAL SCREENING');assert.equal(x.stressConsistent,false);assert.deepEqual(x.rows.map(r=>r.country),['IRL','FIN','CAN']);for(const r of x.rows)for(const k of ['base','delay','half'])assert.equal(r.cases[k].alternatives.length,3);});
test('lease break-even frontier matches full model across countries and stress cases',()=>{for(const country of ['IRL','FIN','CAN'])for(const c of ['base','delay','half']){const x=evaluate({country},c),ranges=x.leaseEconomics.ranges;assert.deepEqual(ranges.map(r=>r.strategy),['LEASE','HYBRID','BUILD']);for(const r of ranges){const price=r.upper===null?r.lower+1:(r.lower+r.upper)/2;const y=evaluate({country},c,{...FIXED,leasePerHour:price});assert.equal(y.recommendation.verdict,r.strategy);for(const line of x.leaseEconomics.lines){const a=y.alternatives.find(a=>a.strategy===line.strategy);assert.ok(Math.abs(a.discounted-(line.intercept+line.slope*price))<.001)}}for(let i=1;i<ranges.length;i++){const p=ranges[i].lower,y=evaluate({country},c,{...FIXED,leasePerHour:p});const a=y.alternatives.find(a=>a.strategy===ranges[i-1].strategy),b=y.alternatives.find(a=>a.strategy===ranges[i].strategy);assert.ok(Math.abs(a.discounted-b.discounted)<.001)}}});
test('rental price reverses preferences without changing demand or granting approval',()=>{const a=evaluate({},'base',{...FIXED,leasePerHour:4.5}),b=evaluate({},'base',{...FIXED,leasePerHour:9});assert.equal(a.recommendation.verdict,'HYBRID');assert.equal(b.recommendation.verdict,'BUILD');assert.equal(a.demandHours,b.demandHours);assert.equal(b.recommendation.approval.status,'MORE EVIDENCE REQUIRED');});

test('researched currency conversions, distinct regional pricing and billed-hour accounting',()=>{assert.ok(Math.abs(COST_EVIDENCE.countries.IRL.electricityUsd-.1724*1.5782/1.3978)<1e-12);assert.ok(Math.abs(COST_EVIDENCE.countries.FIN.electricityUsd-(.0416+.02325)*1.5782/1.3978)<1e-12);assert.ok(Math.abs(COST_EVIDENCE.countries.CAN.electricityUsd-.13/1.3978)<1e-12);for(const country of ['IRL','FIN','CAN']){const x=evaluate({country});const lease=x.alternatives.find(a=>a.strategy==='LEASE');assert.equal(x.leaseEconomics.assumedBaseUsdPerHour,COST_EVIDENCE.countries[country].leaseUsd);assert.ok(Math.abs(lease.rows[1].lease-FIXED.baselineDemandHours/.95*COST_EVIDENCE.countries[country].leaseUsd*1.1)<.001);assert.equal(x.recommendation.approval.status,'MORE EVIDENCE REQUIRED');}});
test('researched cases show derived country differences and keep a common workload',()=>{const expected={IRL:['BUILD','HYBRID','HYBRID'],FIN:['HYBRID','HYBRID','LEASE'],CAN:['BUILD','HYBRID','LEASE']};for(const [country,winners] of Object.entries(expected))['base','delay','half'].forEach((name,i)=>{const x=evaluate({country},name);assert.equal(x.recommendation.verdict,winners[i]);assert.ok(x.alternatives.every(a=>a.productiveHours===x.alternatives[0].productiveHours));});});


test('ownership benchmarks distinguish complete server price and construction premium',()=>{assert.equal(FIXED.gpuPrice,319924/8);assert.ok(Math.abs(FIXED.facilityPerMw-11300000*1.1)<1e-6);assert.equal(COST_EVIDENCE.ownership.gpuPriceRange[0],316184/8);});
test('robustness recalculates every country and case and reports actual reversals',async()=>{const {robustness}=await import('../lib/shared/model.ts');const r=robustness();assert.equal(r.status,'ASSUMPTION-SENSITIVE');assert.equal(r.rows.length,15);assert.deepEqual(r.distinctBasePreferences,['FIN:HYBRID','FIN:BUILD','FIN:LEASE']);for(const p of r.rows)for(const name of ['base','delay','half']){const f={...FIXED,...p.changes};const all=['IRL','FIN','CAN'].flatMap(country=>evaluate({country},name,f).alternatives.map(a=>({...a,country}))).sort((a,b)=>a.discounted-b.discounted);assert.equal(p.cases[name].country,all[0].country);assert.equal(p.cases[name].strategy,all[0].strategy);assert.equal(p.cases[name].discounted,all[0].discounted);}});
test('retained lease allocation bills idle reserved footprint without inventing delivered work',()=>{const f={...FIXED,leaseCommitmentFraction:1};const base=evaluate({},'base',f),half=evaluate({},'half',f);for(let i=0;i<3;i++){assert.equal(half.alternatives[i].productiveHours,base.alternatives[i].productiveHours/2);assert.ok(half.alternatives[i].total>=evaluate({},'half').alternatives[i].total);for(const row of half.alternatives[i].rows){assert.ok(row.billedGpuHours*FIXED.leaseProductiveFraction+1e-6>=row.leasedHours);assert.ok(row.billedGpuHours*FIXED.leaseProductiveFraction+1e-6>=row.forecastLeasedHours);assert.equal(row.total,row.facility+row.grid+row.gpus+row.otherIt+row.replacement+row.operating+row.interest);}}assert.ok(half.alternatives[1].capitalAtRisk>0);assert.throws(()=>evaluate({},'base',{...FIXED,leaseCommitmentFraction:1.2}));});
test('productive conversion changes costs without changing delivered workload',()=>{const a=evaluate(),b=evaluate({},'base',{...FIXED,leaseProductiveFraction:.7});for(let i=0;i<3;i++){assert.equal(a.alternatives[i].productiveHours,b.alternatives[i].productiveHours);assert.ok(b.alternatives[i].total>a.alternatives[i].total);}});
