export const MODEL_VERSION='1.1.0';
export const DEFAULTS={itLoadMw:20,pue:1.25,utilization:0.6,electricityMultiplier:1,gpuMultiplier:1,facilityMultiplier:1,delayMonths:0,country:'FIN'};
export const FIXED={reference:'NVIDIA H100 SXM 80GB planning-equivalent GPU',systemKwPerGpu:1.4,nonGpuShare:0.1,usableFraction:0.95,idleFraction:0.35,baselineDemandHours:64197572.4,facilityPerMw:8000000,gpuPrice:30000,otherItPerMw:1500000,gridPerMw:500000,staffPerMw:180000,leasePerHour:3,leaseSupport:0.1,tariffs:{IRL:0.15,FIN:0.10,CAN:0.10},discount:0.08,debtShare:0.6,interest:0.06,tenor:7,gpuLife:4,otherItLife:5,openingMonth:24};
export const GAPS=['Signed member demand and workload equivalence','Site-specific utility capacity, upgrade cost and energization offer','Comparable delivered lease price and construction/vendor quotes'];
export function energy(mw:number,pue:number,hours=8760){if(!Number.isFinite(mw)||!Number.isFinite(pue)||!Number.isFinite(hours)||mw<0||pue<1||hours<0)throw Error('Invalid energy inputs');return {facilityMw:mw*pue,annualGwh:mw*pue*hours/1000};}
export function normalize(input:any={}){const a={...DEFAULTS,...input};const ranges:any={itLoadMw:[5,30,1],pue:[1.1,1.6,.05],utilization:[.1,.9,.05],electricityMultiplier:[.5,2,.1],gpuMultiplier:[.75,1.5,.05],facilityMultiplier:[.75,1.5,.05]};for(const [k,r] of Object.entries(ranges) as any){if(typeof a[k]!=='number'||!Number.isFinite(a[k])||a[k]<r[0]-1e-9||a[k]>r[1]+1e-9||Math.abs((a[k]-r[0])/r[2]-Math.round((a[k]-r[0])/r[2]))>1e-6)throw Error('Out of bounds: '+k);}if(![0,6,12,18,24].includes(a.delayMonths)||!['IRL','FIN','CAN'].includes(a.country))throw Error('Invalid country or delay');return a;}
export function rank(costs:any[],gaps:string[]=GAPS){
 const approval={status:gaps.length?'MORE EVIDENCE REQUIRED':'READY FOR INDEPENDENT REVIEW',gaps};
 const unresolved=(rationale:string)=>({verdict:'INSUFFICIENT EVIDENCE',conditional:true,rationale,approval,runnerUp:null,savingsVsRunnerUp:null});
 if(!costs.length||costs.some(a=>!Number.isFinite(a.discounted)||a.discounted<0||(a.productiveHours!==undefined&&(!Number.isFinite(a.productiveHours)||a.productiveHours<=0))))return unresolved('Missing valid costs or productive workload prevents a screening comparison.');
 const feasible=costs.filter(a=>(a.unmetHours??0)===0);if(!feasible.length)return unresolved('No alternative delivers the required workload.');
 const hours=feasible.map(a=>a.productiveHours).filter(h=>h!==undefined);if(hours.length&&Math.max(...hours)-Math.min(...hours)>1)return unresolved('Alternatives do not deliver equivalent productive GPU-hours.');
 const sorted=[...feasible].sort((a,b)=>a.discounted-b.discounted);
 if(sorted[1]&&sorted[0].discounted===sorted[1].discounted)return unresolved('Lowest discounted costs are exactly tied: '+sorted.filter(a=>a.discounted===sorted[0].discounted).map(a=>a.strategy).join(', ')+'.');
 return {verdict:sorted[0].strategy,runnerUp:sorted[1]?.strategy??null,conditional:true,rationale:'Conditional screening preference: lowest discounted ten-year cash cost for equivalent delivered workload under the displayed assumptions. This is not investment approval.',approval,savingsVsRunnerUp:sorted[1]?sorted[1].discounted-sorted[0].discounted:null};
}
export function evaluate(input:any={},caseName='custom',fixed:any=FIXED){const a=normalize(input), demand=fixed.baselineDemandHours*(caseName==='half'?0.5:1),u=caseName==='half'?a.utilization/2:a.utilization,opening=(fixed.openingMonth+(caseName==='delay'?12:a.delayMonths))/12;const alternatives=['BUILD','LEASE','HYBRID'].map(strategy=>{const rows:any[]=[],tranches:any[]=[],debts:any[]=[];let before=0,equityBefore=0,capital=0;for(let t=0;t<=10;t++){const row:any={year:t,facility:0,grid:0,gpus:0,otherIt:0,electricity:0,staffing:0,maintenance:0,lease:0,replacement:0,financing:0,debtDraw:0,equityDraw:0,principal:0,interest:0,outstanding:0,productiveHours:t?demand:0,ownedHours:0,leasedHours:0,unusedHours:0,energyKwh:0,unmetHours:0};
const initialMw=strategy==='LEASE'?0:strategy==='BUILD'?a.itLoadMw:a.itLoadMw*.5; if(t===0)row.facility=initialMw*fixed.facilityPerMw*a.facilityMultiplier*.1;
const schedule=strategy==='LEASE'?[]:strategy==='BUILD'?[{start:opening,mw:a.itLoadMw,initial:true}]:[{start:opening,mw:a.itLoadMw*.5,initial:true},{start:Math.max(3,opening),mw:a.itLoadMw*.5,initial:false}];
for(const s of schedule){if(Math.floor(s.start)===t){const n=Math.floor(s.mw*1000*(1-fixed.nonGpuShare)/fixed.systemKwPerGpu);tranches.push({...s,n});row.facility+=s.mw*fixed.facilityPerMw*a.facilityMultiplier*(s.initial?.9:1);row.grid+=s.mw*fixed.gridPerMw;row.gpus+=n*fixed.gpuPrice*a.gpuMultiplier;row.otherIt+=s.mw*fixed.otherItPerMw;}}
let available=0,activeMw=0;for(const s of tranches){const fraction=t?Math.max(0,Math.min(1,t-s.start)):0;available+=s.n*fixed.usableFraction*8760*fraction;activeMw+=s.mw*fraction;if(t>Math.floor(s.start)&& (t-Math.floor(s.start))%fixed.gpuLife===0)row.replacement+=s.n*fixed.gpuPrice*a.gpuMultiplier;if(t>Math.floor(s.start)&& (t-Math.floor(s.start))%fixed.otherItLife===0)row.replacement+=s.mw*fixed.otherItPerMw;}
row.ownedHours=Math.min(row.productiveHours,available*u);row.leasedHours=row.productiveHours-row.ownedHours;row.unusedHours=available-row.ownedHours;row.lease=row.leasedHours*fixed.leasePerHour*(1+fixed.leaseSupport);row.realizedOwnedUtilization=available?row.ownedHours/available:0;row.energyKwh=activeMw*(fixed.idleFraction+(1-fixed.idleFraction)*row.realizedOwnedUtilization)*a.pue*8760*1000;row.electricity=row.energyKwh*fixed.tariffs[a.country]*a.electricityMultiplier;row.staffing=activeMw*fixed.staffPerMw;row.maintenance=activeMw*fixed.facilityPerMw*a.facilityMultiplier*.02;
const capex=row.facility+row.grid+row.gpus+row.otherIt+row.replacement;row.debtDraw=capex*fixed.debtShare;row.equityDraw=capex-row.debtDraw;if(row.debtDraw)debts.push({balance:row.debtDraw,annual:row.debtDraw/fixed.tenor,start:t});for(const d of debts){if(t>=d.start&&d.balance>0){row.interest+=d.balance*fixed.interest;const principal=t>d.start?Math.min(d.balance,d.annual):0;row.principal+=principal;d.balance-=principal;row.outstanding+=d.balance;}}row.financing=row.interest;row.operating=row.electricity+row.staffing+row.maintenance+row.lease;row.total=capex+row.operating+row.financing;row.unusedAllocation=available?(1-row.ownedHours/available)*(row.staffing+row.maintenance+capex):0;
if(strategy!=='LEASE'&&t<=Math.floor(opening)){before+=row.total;equityBefore+=row.equityDraw+row.operating+row.financing;capital+=row.facility+row.grid+row.gpus+row.otherIt;}rows.push(row);}
const sum=(k:string)=>rows.reduce((v,r)=>v+r[k],0),discounted=rows.reduce((v,r)=>v+r.total/Math.pow(1+fixed.discount,r.year),0),dh=rows.reduce((v,r)=>v+r.productiveHours/Math.pow(1+fixed.discount,r.year),0);return {strategy,rows,total:sum('total'),discounted,cashBeforeOpening:before,equityBeforeOpening:equityBefore,capitalAtRisk:capital,representativeOperating:rows[5].operating,costPerHour:demand?sum('total')/(demand*10):null,levelized:dh?discounted/dh:null,productiveHours:sum('productiveHours'),ownedHours:sum('ownedHours'),leasedHours:sum('leasedHours'),unmetHours:sum('unmetHours'),energyKwh:sum('energyKwh')};});return {modelVersion:MODEL_VERSION,inputs:a,caseName,energy:energy(a.itLoadMw,a.pue),demandHours:demand,openingYear:opening,alternatives,recommendation:{...rank(alternatives),caseEffect:caseName==='half'?'Productive demand halves while the installed owned fleet, capital and staffing remain fixed; idle power prevents electricity cost from halving. Lease spending follows delivered GPU-hours.':caseName==='delay'?'Owned commissioning is delayed one year; bridge leasing and pre-opening exposure rise. Replacement timing shifts within the fixed ten-year horizon; omitted salvage may reduce reported ownership cost and must not be read as a benefit of delay.':'Ownership requires facility and GPU capital, replacements and operating costs; leasing avoids owned capital exposure under the assumed cancellable service contract. Costs and workload equivalence are planning assumptions.'},gaps:GAPS,limitations:['All cost and demand inputs are illustrative planning assumptions in constant 2026 USD, not quotes.','Opening at month 24; uniform productive GPU-hours do not prove performance equivalence.','No inflation, tax, salvage, grants or cancellability costs; lender terms unverified.','Debt principal and unused allocation are reported separately and never added to economic cost.']};}
export function sensitivity(input:any){const base=evaluate(input);const fields:any={itLoadMw:[5,30,1],pue:[1.1,1.6,.05],utilization:[.1,.9,.05],electricityMultiplier:[.5,2,.1],gpuMultiplier:[.75,1.5,.05],facilityMultiplier:[.75,1.5,.05],delayMonths:[0,24,6]};return Object.entries(fields).map(([key,r]:any)=>{const points:any[]=[];for(let v=r[0];v<=r[1]+1e-7;v+=r[2]){const x=evaluate({...base.inputs,[key]:Number(v.toFixed(4))});points.push({value:Number(v.toFixed(4)),verdict:x.recommendation.verdict,illustrativeLowest:[...x.alternatives].sort((a,b)=>a.discounted-b.discounted)[0].strategy});}const reversals=points.slice(1).flatMap((p,i)=>p.verdict===points[i].verdict?[]:[{lower:points[i].value,upper:p.value,from:points[i].verdict,to:p.verdict}]);return {input:key,points,reversals};});}

export function overallScreening(input:any={},fixed:any=FIXED){
 const rows=['IRL','FIN','CAN'].map(country=>{const inputs={...normalize(input),country,delayMonths:0};return {country,cases:Object.fromEntries(['base','delay','half'].map(k=>[k,evaluate(inputs,k,fixed)]))};});
 const preferences=rows.map(r=>r.cases.base.recommendation.verdict);
 const strategy=preferences.every(v=>v===preferences[0])?preferences[0]:'COUNTRY-DEPENDENT';
 const stressConsistent=rows.every(r=>['delay','half'].every(k=>r.cases[k].recommendation.verdict===strategy));
 return {strategy,conditional:true,countryStatus:'UNRESOLVED',stressConsistent,rows,rationale:strategy==='COUNTRY-DEPENDENT'?'The modeled strategy preference differs by country; review the country results before choosing.':'The same strategy has the lowest modeled discounted cost in all three country scenarios.',countryRationale:'No defensible country winner is established: lease pricing is the same illustrative assumption across countries, Finland and Canada share the same electricity proxy, and site capacity, delivered quotes, workload latency and jurisdiction requirements remain unresolved. National energy statistics do not establish site readiness.'};
}
