import pricing from '../../db/seed/pricing.json' with {type:'json'};
export const COST_EVIDENCE=pricing;
export const MODEL_VERSION='1.4.0';
export const DEFAULTS={itLoadMw:20,pue:1.25,utilization:0.6,electricityMultiplier:1,gpuMultiplier:1,facilityMultiplier:1,delayMonths:0,country:'FIN'};
export const FIXED={reference:'NVIDIA H100 SXM 80GB planning-equivalent GPU',systemKwPerGpu:1.4,nonGpuShare:0.1,usableFraction:0.95,idleFraction:0.35,baselineDemandHours:64197572.4,facilityPerMw:pricing.ownership.facilityPerMw,gpuPrice:pricing.ownership.gpuPrice,otherItPerMw:1500000,gridPerMw:500000,staffPerMw:180000,pricingVersion:pricing.version,leasePerHour:null,leaseByCountry:Object.fromEntries(Object.entries(pricing.countries).map(([k,v])=>[k,v.leaseUsd])),leaseProductiveFraction:pricing.leaseProductiveFraction,leaseSupport:0.1,leaseCommitmentFraction:0,tariffs:Object.fromEntries(Object.entries(pricing.countries).map(([k,v])=>[k,v.electricityUsd])),discount:0.08,debtShare:0.6,interest:0.06,tenor:7,gpuLife:4,otherItLife:5,openingMonth:24};
export const GAPS=['Signed member demand and workload equivalence','Site-specific utility capacity, upgrade cost and energization offer','Comparable delivered lease price and construction/vendor quotes'];
export function energy(mw:number,pue:number,hours=8760){if(!Number.isFinite(mw)||!Number.isFinite(pue)||!Number.isFinite(hours)||mw<0||pue<1||hours<0)throw Error('Invalid energy inputs');return {facilityMw:mw*pue,annualGwh:mw*pue*hours/1000};}
export function normalize(input:any={}){const a={...DEFAULTS,...input};const ranges:any={itLoadMw:[5,30,1],pue:[1.1,1.6,.05],utilization:[.1,.9,.05],electricityMultiplier:[.5,2,.1],gpuMultiplier:[.75,1.5,.05],facilityMultiplier:[.75,1.5,.05]};for(const [k,r] of Object.entries(ranges) as any){if(typeof a[k]!=='number'||!Number.isFinite(a[k])||a[k]<r[0]-1e-9||a[k]>r[1]+1e-9||Math.abs((a[k]-r[0])/r[2]-Math.round((a[k]-r[0])/r[2]))>1e-6)throw Error('Out of bounds: '+k);}if(![0,6,12,18,24].includes(a.delayMonths)||!['IRL','FIN','CAN'].includes(a.country))throw Error('Invalid country or delay');return a;}
export function rank(costs:any[],gaps:string[]=GAPS){
 const approval={status:gaps.length?'MORE EVIDENCE REQUIRED':'READY FOR INDEPENDENT REVIEW',gaps};
 const unresolved=(rationale:string)=>({verdict:'INSUFFICIENT EVIDENCE',conditional:true,rationale,approval,runnerUp:null,savingsVsRunnerUp:null});
 if(!costs.length||costs.some(a=>!Number.isFinite(a.discounted)||a.discounted<0||(a.productiveHours!==undefined&&(!Number.isFinite(a.productiveHours)||a.productiveHours<=0))))return unresolved('Missing valid costs or productive workload prevents a screening comparison.');
 const feasible=costs.filter(a=>(a.unmetHours??0)===0);if(!feasible.length)return unresolved('No alternative delivers the required workload.');
 const hours=feasible.map(a=>a.productiveHours).filter(h=>h!==undefined);if(hours.length&&Math.max(...hours)-Math.min(...hours)>1)return unresolved('Alternatives do not deliver equivalent productive GPU-hours.');
 const sorted=[...feasible].sort((a,b)=>a.discounted-b.discounted);
 if(sorted[1]&&sorted[0].discounted===sorted[1].discounted)return unresolved('Lowest discounted costs are exactly tied: '+sorted.filter(a=>a.discounted===sorted[0].discounted).map(a=>a.strategy).join(', ')+'.');
 return {verdict:sorted[0].strategy,runnerUp:sorted[1]?.strategy??null,conditional:true,rationale:'Conditional screening preference: lowest discounted ten-year cash cost for equivalent delivered workload under the displayed assumptions. This is not investment approval.',approval,savingsVsRunnerUp:sorted[1]?sorted[1].discounted-sorted[0].discounted:null};
}
export function evaluate(input:any={},caseName='custom',fixed:any=FIXED){const a=normalize(input);fixed={...fixed,leasePerHour:fixed.leasePerHour??fixed.leaseByCountry?.[a.country],leaseProductiveFraction:fixed.leaseProductiveFraction??1};if(!Number.isFinite(fixed.leaseCommitmentFraction??0)||(fixed.leaseCommitmentFraction??0)<0||(fixed.leaseCommitmentFraction??0)>1)throw Error('Invalid lease commitment');if(!(fixed.leasePerHour>=0)||!(fixed.leaseProductiveFraction>0&&fixed.leaseProductiveFraction<=1))throw Error('Invalid lease basis');const demand=fixed.baselineDemandHours*(caseName==='half'?0.5:1),u=caseName==='half'?a.utilization/2:a.utilization,opening=(fixed.openingMonth+(caseName==='delay'?12:a.delayMonths))/12;const alternatives=['BUILD','LEASE','HYBRID'].map(strategy=>{const rows:any[]=[],tranches:any[]=[],debts:any[]=[];let before=0,equityBefore=0,capital=0;for(let t=0;t<=10;t++){const row:any={year:t,facility:0,grid:0,gpus:0,otherIt:0,electricity:0,staffing:0,maintenance:0,lease:0,replacement:0,financing:0,debtDraw:0,equityDraw:0,principal:0,interest:0,outstanding:0,productiveHours:t?demand:0,ownedHours:0,leasedHours:0,unusedHours:0,energyKwh:0,unmetHours:0};
const initialMw=strategy==='LEASE'?0:strategy==='BUILD'?a.itLoadMw:a.itLoadMw*.5; if(t===0)row.facility=initialMw*fixed.facilityPerMw*a.facilityMultiplier*.1;
const schedule=strategy==='LEASE'?[]:strategy==='BUILD'?[{start:opening,mw:a.itLoadMw,initial:true}]:[{start:opening,mw:a.itLoadMw*.5,initial:true},{start:Math.max(3,opening),mw:a.itLoadMw*.5,initial:false}];
for(const s of schedule){if(Math.floor(s.start)===t){const n=Math.floor(s.mw*1000*(1-fixed.nonGpuShare)/fixed.systemKwPerGpu);tranches.push({...s,n});row.facility+=s.mw*fixed.facilityPerMw*a.facilityMultiplier*(s.initial?.9:1);row.grid+=s.mw*fixed.gridPerMw;row.gpus+=n*fixed.gpuPrice*a.gpuMultiplier;row.otherIt+=s.mw*fixed.otherItPerMw;}}
let available=0,activeMw=0;for(const s of tranches){const fraction=t?Math.max(0,Math.min(1,t-s.start)):0;available+=s.n*fixed.usableFraction*8760*fraction;activeMw+=s.mw*fraction;if(t>Math.floor(s.start)&& (t-Math.floor(s.start))%fixed.gpuLife===0)row.replacement+=s.n*fixed.gpuPrice*a.gpuMultiplier;if(t>Math.floor(s.start)&& (t-Math.floor(s.start))%fixed.otherItLife===0)row.replacement+=s.mw*fixed.otherItPerMw;}
row.ownedHours=Math.min(row.productiveHours,available*u);row.leasedHours=row.productiveHours-row.ownedHours;row.unusedHours=available-row.ownedHours;row.forecastLeasedHours=t?Math.max(0,fixed.baselineDemandHours-available*a.utilization):0;row.billedGpuHours=Math.max(row.leasedHours,row.forecastLeasedHours*(fixed.leaseCommitmentFraction??0))/fixed.leaseProductiveFraction;row.lease=row.billedGpuHours*fixed.leasePerHour*(1+fixed.leaseSupport);row.realizedOwnedUtilization=available?row.ownedHours/available:0;row.energyKwh=activeMw*(fixed.idleFraction+(1-fixed.idleFraction)*row.realizedOwnedUtilization)*a.pue*8760*1000;row.electricity=row.energyKwh*fixed.tariffs[a.country]*a.electricityMultiplier;row.staffing=activeMw*fixed.staffPerMw;row.maintenance=activeMw*fixed.facilityPerMw*a.facilityMultiplier*.02;
const capex=row.facility+row.grid+row.gpus+row.otherIt+row.replacement;row.debtDraw=capex*fixed.debtShare;row.equityDraw=capex-row.debtDraw;if(row.debtDraw)debts.push({balance:row.debtDraw,annual:row.debtDraw/fixed.tenor,start:t});for(const d of debts){if(t>=d.start&&d.balance>0){row.interest+=d.balance*fixed.interest;const principal=t>d.start?Math.min(d.balance,d.annual):0;row.principal+=principal;d.balance-=principal;row.outstanding+=d.balance;}}row.financing=row.interest;row.operating=row.electricity+row.staffing+row.maintenance+row.lease;row.total=capex+row.operating+row.financing;row.unusedAllocation=available?(1-row.ownedHours/available)*(row.staffing+row.maintenance+capex):0;
if(strategy!=='LEASE'&&t<=Math.floor(opening)){before+=row.total;equityBefore+=row.equityDraw+row.operating+row.financing;capital+=row.facility+row.grid+row.gpus+row.otherIt;}rows.push(row);}
const sum=(k:string)=>rows.reduce((v,r)=>v+r[k],0),discounted=rows.reduce((v,r)=>v+r.total/Math.pow(1+fixed.discount,r.year),0),dh=rows.reduce((v,r)=>v+r.productiveHours/Math.pow(1+fixed.discount,r.year),0);return {strategy,rows,total:sum('total'),discounted,cashBeforeOpening:before,equityBeforeOpening:equityBefore,capitalAtRisk:capital+(fixed.leaseCommitmentFraction??0)*rows[1].forecastLeasedHours/fixed.leaseProductiveFraction*fixed.leasePerHour*(1+fixed.leaseSupport),representativeOperating:rows[5].operating,costPerHour:demand?sum('total')/(demand*10):null,levelized:dh?discounted/dh:null,productiveHours:sum('productiveHours'),ownedHours:sum('ownedHours'),leasedHours:sum('leasedHours'),unmetHours:sum('unmetHours'),energyKwh:sum('energyKwh')};});return {modelVersion:MODEL_VERSION,inputs:a,caseName,energy:energy(a.itLoadMw,a.pue),demandHours:demand,openingYear:opening,alternatives,leaseEconomics:leaseEconomics(alternatives,fixed),recommendation:{...rank(alternatives),caseEffect:caseName==='half'?'Productive demand halves while the installed owned fleet, capital and staffing remain fixed; idle power prevents electricity cost from halving. Lease spending follows delivered GPU-hours.':caseName==='delay'?'Owned commissioning is delayed one year; bridge leasing and pre-opening exposure rise. Replacement timing shifts within the fixed ten-year horizon; omitted salvage may reduce reported ownership cost and must not be read as a benefit of delay.':'Ownership requires facility and GPU capital, replacements and operating costs; leasing avoids owned capital exposure under the assumed cancellable service contract. Costs and workload equivalence are planning assumptions.'},gaps:GAPS,limitations:['Country power and rental inputs use cited public benchmarks; conversions and workload mapping are calculations/assumptions, not delivered offers.','Opening at month 24; uniform productive GPU-hours do not prove performance equivalence.','No inflation, corporate tax, salvage, grants or cancellability costs; Finnish electricity tax is included in its proxy; lender terms unverified.','Debt principal and unused allocation are reported separately and never added to economic cost.']};}
export function sensitivity(input:any){const base=evaluate(input);const fields:any={itLoadMw:[5,30,1],pue:[1.1,1.6,.05],utilization:[.1,.9,.05],electricityMultiplier:[.5,2,.1],gpuMultiplier:[.75,1.5,.05],facilityMultiplier:[.75,1.5,.05],delayMonths:[0,24,6]};return Object.entries(fields).map(([key,r]:any)=>{const points:any[]=[];for(let v=r[0];v<=r[1]+1e-7;v+=r[2]){const x=evaluate({...base.inputs,[key]:Number(v.toFixed(4))});points.push({value:Number(v.toFixed(4)),verdict:x.recommendation.verdict,illustrativeLowest:[...x.alternatives].sort((a,b)=>a.discounted-b.discounted)[0].strategy});}const reversals=points.slice(1).flatMap((p,i)=>p.verdict===points[i].verdict?[]:[{lower:points[i].value,upper:p.value,from:points[i].verdict,to:p.verdict}]);return {input:key,points,reversals};});}

export function overallScreening(input:any={},fixed:any=FIXED){
 const rows=['IRL','FIN','CAN'].map(country=>{const inputs={...normalize(input),country,delayMonths:0};return {country,cases:Object.fromEntries(['base','delay','half'].map(k=>[k,evaluate(inputs,k,fixed)]))};});
 const preferences=rows.map(r=>r.cases.base.recommendation.verdict);
 const strategy=preferences.every(v=>v===preferences[0])?preferences[0]:'COUNTRY-DEPENDENT';
 const stressConsistent=rows.every(r=>['delay','half'].every(k=>r.cases[k].recommendation.verdict===strategy));
 const candidates=rows.flatMap(r=>r.cases.base.alternatives.map((a:any)=>({country:r.country,strategy:a.strategy,discounted:a.discounted}))).sort((a,b)=>a.discounted-b.discounted);
 const preference={...candidates[0],runnerUp:candidates[1],savingsVsRunnerUp:candidates[1].discounted-candidates[0].discounted};
 return {strategy:preference.strategy,conditional:true,countryStatus:'CONDITIONAL SCREENING',countryPreference:preference.country,preference,robustness:robustness(input,fixed,preference),stressConsistent:rows.find(r=>r.country===preference.country)?.cases.delay.recommendation.verdict===preference.strategy&&rows.find(r=>r.country===preference.country)?.cases.half.recommendation.verdict===preference.strategy,rows,rationale:'Among the nine country/strategy combinations, this has the lowest modeled discounted ten-year cost under the saved baseline and researched price benchmarks. Country and provider selection are provisional: advertised hardware and contract scopes differ.',countryRationale:'Prioritize this country/strategy for further diligence, conditional on comparable workload performance and deliverable capacity. This is a transparent cost-screening preference, not an approved location or an exhaustive market ranking. Utility capacity, connection costs, supplier allocation, member latency and jurisdiction requirements still need confirmation.'};
}

// Affine lease-price diagnostic: bridge and overflow prices change for every strategy.
export function leaseEconomics(alternatives:any[],fixed:any=FIXED){
 const lines=alternatives.map(a=>{const slope=a.rows.reduce((v:number,r:any)=>v+(r.billedGpuHours??r.leasedHours/(fixed.leaseProductiveFraction??1))*(1+fixed.leaseSupport)/Math.pow(1+fixed.discount,r.year),0);return {strategy:a.strategy,slope,intercept:a.discounted-slope*fixed.leasePerHour};});
 const intersections:number[]=[];for(let i=0;i<lines.length;i++)for(let j=i+1;j<lines.length;j++){const a=lines[i],b=lines[j];if(a.slope!==b.slope){const p=(b.intercept-a.intercept)/(a.slope-b.slope);if(Number.isFinite(p)&&p>0)intersections.push(p);}}
 const boundaries=[0,...new Set(intersections.sort((a,b)=>a-b))];
 const intervals=boundaries.map((lower,i)=>{const upper=boundaries[i+1]??null,p=upper===null?lower+Math.max(1,lower):(lower+upper)/2;const winner=[...lines].sort((a,b)=>(a.intercept+a.slope*p)-(b.intercept+b.slope*p))[0];return {lower,upper,strategy:winner.strategy};});
 const ranges:any[]=[];for(const x of intervals){const last=ranges.at(-1);if(last?.strategy===x.strategy)last.upper=x.upper;else ranges.push({...x});}
 return {assumedBaseUsdPerHour:fixed.leasePerHour,supportFraction:fixed.leaseSupport,productiveFraction:fixed.leaseProductiveFraction??1,ranges,lines,interpretation:'Calculated break-even rental prices per billed allocated GPU-hour, before the fixed support allowance and productive-hour conversion. Applies the same price to lease-only, bridge and overflow; holds all other assumptions fixed. These are model thresholds, not supplier quotes.'};
}

// Fixed diagnostic scenarios, not extra visitor controls or probability distributions.
export function robustness(input:any={},fixed:any=FIXED,reference?:any){
 const a=normalize(input);
 const presets=[
 {id:'benchmark',label:'Benchmark inputs',basis:'Public price benchmarks; remaining planning assumptions',changes:{}},
 {id:'construction-low',label:'Construction −20%',basis:'Analyst cost stress, not a source confidence interval',changes:{facilityPerMw:fixed.facilityPerMw*.8}},
 {id:'construction-high',label:'Construction +20%',basis:'Analyst cost stress, not a source confidence interval',changes:{facilityPerMw:fixed.facilityPerMw*1.2}},
 {id:'server-low',label:'Published lower server configuration',basis:'Exxact Professional / eight GPUs',changes:{gpuPrice:pricing.ownership.gpuPriceRange[0]}},
 {id:'server-high',label:'Published higher server configuration',basis:'Exxact Premium / eight GPUs',changes:{gpuPrice:pricing.ownership.gpuPriceRange[1]}},
 {id:'productive-low',label:'70% productive conversion',basis:'Analyst throughput/billing stress; not measured equivalence',changes:{leaseProductiveFraction:.7}},
 {id:'productive-high',label:'100% productive conversion',basis:'Idealized upper bound; not a provider promise',changes:{leaseProductiveFraction:1}},
 {id:'allocated',label:'Retain forecast rental allocation',basis:'Bill annual planned leased footprint even if demand falls; hypothetical rolling one-year obligation, no discount',changes:{leaseCommitmentFraction:1}},
 {id:'power-reference',label:'Rated node power allocation',basis:'NVIDIA 10.2kW / eight GPUs; demand held fixed',changes:{systemKwPerGpu:1.275}},
 {id:'idle-reference',label:'Measured-node idle reference',basis:'Single-study idle/rated ratio 1.86 / 10.2, not fleet telemetry',changes:{idleFraction:1.86/10.2}},
 {id:'refresh-five',label:'Five-year server refresh',basis:'JLL approximate IT refresh schedule; not lifetime guarantee',changes:{gpuLife:5}},
 {id:'service-high',label:'30% service allowance',basis:'Analyst storage/support/egress stress; no itemized quote',changes:{leaseSupport:.3}},
 {id:'quebec-lg',label:'Québec existing LG reference',basis:'Published demand and energy charges at assumed 74% load factor; eligibility unconfirmed',changes:{tariffs:{...fixed.tariffs,CAN:(.04324+16.571*12/(8760*.74))/1.3978}}},
 {id:'joint-low',label:'Lower ownership / slower rental productivity',basis:'Joint analyst stress: construction −20%, lower catalog server, 70% productive rental',changes:{facilityPerMw:fixed.facilityPerMw*.8,gpuPrice:pricing.ownership.gpuPriceRange[0],leaseProductiveFraction:.7}},
 {id:'joint-high',label:'Higher ownership / ideal rental productivity',basis:'Joint analyst stress: construction +20%, higher catalog server, 100% productive rental',changes:{facilityPerMw:fixed.facilityPerMw*1.2,gpuPrice:pricing.ownership.gpuPriceRange[1],leaseProductiveFraction:1}}
 ];
 const rows=presets.map(p=>{const f={...fixed,...p.changes};const cases=Object.fromEntries(['base','delay','half'].map(name=>{const candidates=['IRL','FIN','CAN'].flatMap(country=>evaluate({...a,country,delayMonths:0},name,f).alternatives.map((x:any)=>({country,strategy:x.strategy,discounted:x.discounted,productiveHours:x.productiveHours}))).sort((x,y)=>x.discounted-y.discounted);const top=candidates[0],next=candidates[1];return [name,{...top,margin:next.discounted-top.discounted,runnerUp:next}]}));return {id:p.id,label:p.label,basis:p.basis,changes:p.changes,cases};});
 const base=reference??rows[0].cases.base,key=(v:any)=>v.country+':'+v.strategy;
 const stable=rows.every(r=>key(r.cases.base)===key(base));
 return {status:stable?'STABLE IN TESTED SCENARIOS':'ASSUMPTION-SENSITIVE',basePreference:{country:base.country,strategy:base.strategy},distinctBasePreferences:[...new Set(rows.map(r=>key(r.cases.base)))],rows,interpretation:'Fixed one-at-a-time and joint planning stresses, not probabilities, confidence intervals or an exhaustive uncertainty search. Demand and scenario controls are held fixed; three required cases and all nine combinations are recalculated. Site feasibility and workload evidence remain approval gates.'};
}
