export const MODEL_VERSION='1.0.0';
export const DEFAULTS={itLoadMw:20,pue:1.25,utilization:0.6,electricityMultiplier:1,gpuMultiplier:1,facilityMultiplier:1,delayMonths:0,country:'FIN'};
export const FIXED={reference:'NVIDIA H100 SXM 80GB planning-equivalent GPU',systemKwPerGpu:1.4,nonGpuShare:0.1,usableFraction:0.95,idleFraction:0.35,baselineDemandHours:64197572.4,facilityPerMw:8000000,gpuPrice:30000,otherItPerMw:1500000,gridPerMw:500000,staffPerMw:180000,leasePerHour:3,leaseSupport:0.1,tariffs:{IRL:0.15,FIN:0.10,CAN:0.10},discount:0.08,debtShare:0.6,interest:0.06,tenor:7,gpuLife:4,otherItLife:5,openingMonth:24};
export const GAPS=['Signed member demand and workload equivalence','Site-specific utility capacity, upgrade cost and energization offer','Comparable delivered lease price and construction/vendor quotes'];
export function energy(mw:number,pue:number,hours=8760){if(!Number.isFinite(mw)||!Number.isFinite(pue)||!Number.isFinite(hours)||mw<0||pue<1||hours<0)throw Error('Invalid energy inputs');return {facilityMw:mw*pue,annualGwh:mw*pue*hours/1000};}
export function normalize(input:any={}){const a={...DEFAULTS,...input};const ranges:any={itLoadMw:[5,30,1],pue:[1.1,1.6,.05],utilization:[.1,.9,.05],electricityMultiplier:[.5,2,.1],gpuMultiplier:[.75,1.5,.05],facilityMultiplier:[.75,1.5,.05]};for(const [k,r] of Object.entries(ranges) as any){if(typeof a[k]!=='number'||!Number.isFinite(a[k])||a[k]<r[0]-1e-9||a[k]>r[1]+1e-9||Math.abs((a[k]-r[0])/r[2]-Math.round((a[k]-r[0])/r[2]))>1e-6)throw Error('Out of bounds: '+k);}if(![0,6,12,18,24].includes(a.delayMonths)||!['IRL','FIN','CAN'].includes(a.country))throw Error('Invalid country or delay');return a;}
export function rank(costs:any[],gaps:string[]=GAPS){if(gaps.length)return {verdict:'INSUFFICIENT EVIDENCE',conditional:true,rationale:gaps.join('; ')};const sorted=[...costs].sort((a,b)=>a.discounted-b.discounted);if(!sorted.length||!Number.isFinite(sorted[0].discounted)||sorted[0].discounted===sorted[1]?.discounted)return {verdict:'INSUFFICIENT EVIDENCE',conditional:true,rationale:'Missing costs or unresolved exact tie'};return {verdict:sorted[0].strategy,runnerUp:sorted[1]?.strategy,conditional:true,rationale:'Lowest discounted cost among equivalent-workload feasible alternatives'};}
export function evaluate(input:any={},caseName='custom',fixed:any=FIXED){const a=normalize(input), demand=fixed.baselineDemandHours*(caseName==='half'?0.5:1),u=caseName==='half'?a.utilization/2:a.utilization,opening=(fixed.openingMonth+(caseName==='delay'?12:a.delayMonths))/12;const alternatives=['BUILD','LEASE','HYBRID'].map(strategy=>{const rows:any[]=[],tranches:any[]=[],debts:any[]=[];let before=0,equityBefore=0,capital=0;for(let t=0;t<=10;t++){const row:any={year:t,facility:0,grid:0,gpus:0,otherIt:0,electricity:0,staffing:0,maintenance:0,lease:0,replacement:0,financing:0,debtDraw:0,equityDraw:0,principal:0,interest:0,outstanding:0,productiveHours:t?demand:0,ownedHours:0,leasedHours:0,unusedHours:0,energyKwh:0,unmetHours:0};
const initialMw=strategy==='LEASE'?0:strategy==='BUILD'?a.itLoadMw:a.itLoadMw*.5; if(t===0)row.facility=initialMw*fixed.facilityPerMw*a.facilityMultiplier*.1;
const schedule=strategy==='LEASE'?[]:strategy==='BUILD'?[{start:opening,mw:a.itLoadMw,initial:true}]:[{start:opening,mw:a.itLoadMw*.5,initial:true},{start:Math.max(3,opening),mw:a.itLoadMw*.5,initial:false}];
for(const s of schedule){if(Math.floor(s.start)===t){const n=Math.floor(s.mw*1000*(1-fixed.nonGpuShare)/fixed.systemKwPerGpu);tranches.push({...s,n});row.facility+=s.mw*fixed.facilityPerMw*a.facilityMultiplier*(s.initial?.9:1);row.grid+=s.mw*fixed.gridPerMw;row.gpus+=n*fixed.gpuPrice*a.gpuMultiplier;row.otherIt+=s.mw*fixed.otherItPerMw;}}
let available=0,activeMw=0;for(const s of tranches){const fraction=t?Math.max(0,Math.min(1,t-s.start)):0;available+=s.n*fixed.usableFraction*8760*fraction;activeMw+=s.mw*fraction;if(t>Math.floor(s.start)&& (t-Math.floor(s.start))%fixed.gpuLife===0)row.replacement+=s.n*fixed.gpuPrice*a.gpuMultiplier;if(t>Math.floor(s.start)&& (t-Math.floor(s.start))%fixed.otherItLife===0)row.replacement+=s.mw*fixed.otherItPerMw;}
row.ownedHours=Math.min(row.productiveHours,available*u);row.leasedHours=row.productiveHours-row.ownedHours;row.unusedHours=available-row.ownedHours;row.lease=row.leasedHours*fixed.leasePerHour*(1+fixed.leaseSupport);row.realizedOwnedUtilization=available?row.ownedHours/available:0;row.energyKwh=activeMw*(fixed.idleFraction+(1-fixed.idleFraction)*row.realizedOwnedUtilization)*a.pue*8760*1000;row.electricity=row.energyKwh*fixed.tariffs[a.country]*a.electricityMultiplier;row.staffing=activeMw*fixed.staffPerMw;row.maintenance=activeMw*fixed.facilityPerMw*a.facilityMultiplier*.02;
const capex=row.facility+row.grid+row.gpus+row.otherIt+row.replacement;row.debtDraw=capex*fixed.debtShare;row.equityDraw=capex-row.debtDraw;if(row.debtDraw)debts.push({balance:row.debtDraw,annual:row.debtDraw/fixed.tenor,start:t});for(const d of debts){if(t>=d.start&&d.balance>0){row.interest+=d.balance*fixed.interest;const principal=t>d.start?Math.min(d.balance,d.annual):0;row.principal+=principal;d.balance-=principal;row.outstanding+=d.balance;}}row.financing=row.interest;row.operating=row.electricity+row.staffing+row.maintenance+row.lease;row.total=capex+row.operating+row.financing;row.unusedAllocation=available?(1-row.ownedHours/available)*(row.staffing+row.maintenance+capex):0;
if(strategy!=='LEASE'&&t<=Math.floor(opening)){before+=row.total;equityBefore+=row.equityDraw+row.operating+row.financing;capital+=row.facility+row.grid+row.gpus+row.otherIt;}rows.push(row);}
const sum=(k:string)=>rows.reduce((v,r)=>v+r[k],0),discounted=rows.reduce((v,r)=>v+r.total/Math.pow(1+fixed.discount,r.year),0),dh=rows.reduce((v,r)=>v+r.productiveHours/Math.pow(1+fixed.discount,r.year),0);return {strategy,rows,total:sum('total'),discounted,cashBeforeOpening:before,equityBeforeOpening:equityBefore,capitalAtRisk:capital,representativeOperating:rows[5].operating,costPerHour:demand?sum('total')/(demand*10):null,levelized:dh?discounted/dh:null,productiveHours:sum('productiveHours'),ownedHours:sum('ownedHours'),leasedHours:sum('leasedHours'),unmetHours:sum('unmetHours'),energyKwh:sum('energyKwh')};});return {modelVersion:MODEL_VERSION,inputs:a,caseName,energy:energy(a.itLoadMw,a.pue),demandHours:demand,openingYear:opening,alternatives,recommendation:rank(alternatives),gaps:GAPS,limitations:['All cost and demand inputs are illustrative planning assumptions in constant 2026 USD, not quotes.','Opening at month 24; uniform productive GPU-hours do not prove performance equivalence.','No inflation, tax, salvage, grants or cancellability costs; lender terms unverified.','Debt principal and unused allocation are reported separately and never added to economic cost.']};}
export function sensitivity(input:any){const base=evaluate(input);const fields:any={itLoadMw:[5,30,1],pue:[1.1,1.6,.05],utilization:[.1,.9,.05],electricityMultiplier:[.5,2,.1],gpuMultiplier:[.75,1.5,.05],facilityMultiplier:[.75,1.5,.05],delayMonths:[0,24,6]};return Object.entries(fields).map(([key,r]:any)=>{const points=[];for(let v=r[0];v<=r[1]+1e-7;v+=r[2]){const x=evaluate({...base.inputs,[key]:Number(v.toFixed(4))});points.push({value:Number(v.toFixed(4)),verdict:x.recommendation.verdict,illustrativeLowest:[...x.alternatives].sort((a,b)=>a.discounted-b.discounted)[0].strategy});}return {input:key,points};});}
