import fs from 'node:fs';import assert from 'node:assert/strict';
const origin='http://127.0.0.1:5173',headers={'Content-Type':'application/json',Cookie:'__sites_local_auth=1'};const tests=[];
async function call(path,method='GET',data){const r=await fetch(origin+'/api/'+path,{method,headers,body:data===undefined?undefined:JSON.stringify(data)});return {status:r.status,body:await r.json()}}
async function test(name,fn){try{await fn();tests.push({name,status:'pass'})}catch(e){tests.push({name,status:'fail',message:e.message})}}
let old;
await test('local admin canonical PUE revision persists; old revision retained',async()=>{old=(await call('snapshot')).body.data;const r=await call('design','PATCH',{expected_revision:old.design.current_revision,reason:'Local integration PUE test',inputs:{pue:1.4}});assert.equal(r.status,200);const n=(await call('snapshot')).body.data;assert.equal(n.design.pue,1.4);assert.equal(n.design.selected_country_id,null);const result=await call('scenarios/evaluate','POST',{inputs:{}});assert.equal(result.body.data.base.energy.annualGwh,245.28);assert.equal((await call('snapshot')).body.data.design.pue,1.4)});
await test('stale canonical revision rejected409',async()=>assert.equal((await call('design','PATCH',{expected_revision:old.design.current_revision,reason:'Stale integration revision',inputs:{pue:1.25}})).status,409));
await test('last administrator removal rejected409',async()=>{const user=(await call('me')).body.data.user;assert.equal((await call('users/'+user.id+'/role','PATCH',{role:'viewer'})).status,409)});
await test('same-team role lookup refuses nonexistent/cross-team target',async()=>assert.equal((await call('users/foreign/role','PATCH',{role:'admin'})).status,403));
await test('arbitrary external URL/adapter rejected400',async()=>assert.equal((await call('evidence/refresh','POST',{adapter_id:'https://evil.example'})).status,400));
await test('real preview World Bank refresh retains latest observation dates when unchanged',async()=>{const before=(await call('snapshot')).body.data.metrics;const r=await call('evidence/refresh','POST',{adapter_id:'worldbank-renewables'});if(r.status===503){const after=(await call('snapshot')).body.data.metrics;assert.deepEqual(after,before);tests.push({name:'real upstream failure preserves prior values/timestamps',status:'pass'});return;}assert.equal(r.status,200);assert.equal(r.body.data.outcome,'unchanged');assert.deepEqual((await call('snapshot')).body.data.metrics,before)});
await test('invalid source linkage rejected400',async()=>assert.equal((await call('evidence/claims','POST',{text:'Invalid source linkage fixture',type:'fact',source_ids:['missing'],rationale:'Integration negative fixture',uncertainty:'fixture',reason:'Negative integration test'})).status,400));
await test('restore canonical PUE in a new immutable revision',async()=>{const n=(await call('snapshot')).body.data;assert.equal((await call('design','PATCH',{expected_revision:n.design.current_revision,reason:'Restore local test baseline',inputs:{pue:1.25}})).status,200)});
const report={at:new Date().toISOString(),environment:'Real local D1 routes; supported preview identity promoted only in local test database',tests};fs.writeFileSync('reports/tests/preview-admin.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(tests.some(x=>x.status==='fail'))process.exitCode=1;
