import fs from 'node:fs';import {execFileSync} from 'node:child_process';import readline from 'node:readline';import assert from 'node:assert/strict';
if(process.stdin.isTTY)execFileSync('stty',['-echo'],{stdio:'inherit'});process.stdout.write('Ready for deployment access JSON on stdin (input is hidden).\n');const rl=readline.createInterface({input:process.stdin});const config=JSON.parse(await new Promise(r=>rl.once('line',r)));rl.close();const origin=config.origin,tests=[];
async function call(path,method='GET',body,extra={}){const start=Date.now();const r=await fetch(origin+'/api/'+path,{method,headers:{'Content-Type':'application/json','OAI-Sites-Authorization':'Bearer '+config.token,...extra},body:body===undefined?undefined:JSON.stringify(body)});const text=await r.text();let json;try{json=JSON.parse(text)}catch{json={platform_error:true}}return {status:r.status,body:json,ms:Date.now()-start}}
async function test(name,fn){try{await fn();tests.push({name,status:'pass'})}catch(e){tests.push({name,status:'fail',message:e.message})}}
await test('deployed Worker health through supported private service access',async()=>{const r=await call('health');assert.equal(r.status,200);assert.equal(r.body.data.model_version,'1.2.0')});
await test('service access is visitor, not a forged SIWC identity',async()=>assert.equal((await call('me')).status,401));
await test('visitor adviser authorization precedes provider and DB retrieval',async()=>assert.equal((await call('adviser','POST',{question:'Current PUE?'})).status,401));
await test('forged identity headers cannot register via service credential',async()=>assert.equal((await call('register','POST',{course_section:'test',rules_agreed:true},{'oai-authenticated-user-id':'forged','oai-authenticated-user-email':'forged@example.test'})).status,401));
await test('deployed visitor mutations denied',async()=>assert.equal((await call('design','PATCH',{expected_revision:1,reason:'Unauthorized test',inputs:{pue:1.4}})).status,401));
await test('real deployed D1 seed/snapshot available',async()=>{const r=await call('snapshot');assert.equal(r.status,200);assert.equal(r.body.data.metrics.length,3);assert.equal(r.body.data.design.selected_country_id,null);assert.ok(r.body.data.claims.some(c=>c.id==='C20'&&c.supersedes_id==='C5'));assert.ok(r.body.data.sources.some(s=>s.id==='S10')); config.snapshot=r.body.data.hash;config.revision=r.body.data.design.current_revision;});
if(config.snapshot)await test('real deployed calculation under one second, canonical unchanged',async()=>{const r=await call('scenarios/evaluate','POST',{inputs:{pue:1.4}});assert.equal(r.status,200);assert.equal(r.body.data.custom.energy.annualGwh,245.28);assert.ok(r.ms<1000);assert.equal((await call('snapshot')).body.data.design.pue,1.25)});
await test('deployed HTML does not cache obsolete client chunks',async()=>{const r=await fetch(origin+'/?verification=final',{headers:{'OAI-Sites-Authorization':'Bearer '+config.token}});assert.equal(r.status,200);assert.ok(r.headers.get('cache-control').includes('no-store'));});
await test('conditional stress preferences and changing custom scenario retain approval gates',async()=>{const r=await call('scenarios/evaluate','POST',{inputs:{gpuMultiplier:.75},include_sensitivity:true});assert.equal(r.status,200);for(const k of ['base','delay','half']){const c=r.body.data[k];assert.equal(c.recommendation.verdict,'LEASE');assert.equal(c.recommendation.approval.status,'MORE EVIDENCE REQUIRED');}assert.equal(r.body.data.custom.recommendation.verdict,'HYBRID');assert.equal(r.body.data.custom.recommendation.approval.status,'MORE EVIDENCE REQUIRED');assert.ok(r.body.data.sensitivity.some(s=>s.reversals.length));});
const report={at:new Date().toISOString(),environment:'Real deployed Sites Worker/D1; private platform service access supplies no human SIWC identity',deployment:config.deployment,commit:config.commit,origin,snapshot:config.snapshot||null,revision:config.revision||null,tests};fs.writeFileSync('reports/tests/deployed-service.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(tests.some(x=>x.status==='fail'))process.exitCode=1;
