import fs from 'node:fs';import assert from 'node:assert/strict';
const origin=process.env.TEST_ORIGIN||'http://127.0.0.1:5173';const tests=[];
async function call(path,method='GET',data,headers={}){const start=Date.now();const r=await fetch(origin+'/api/'+path,{method,headers:{'Content-Type':'application/json',...headers},body:data===undefined?undefined:JSON.stringify(data)});return {status:r.status,body:await r.text().then(t=>{try{return JSON.parse(t)}catch{return {platform_error:t}}}),ms:Date.now()-start};}
async function check(name,fn){try{await fn();tests.push({name,status:'pass'})}catch(e){tests.push({name,status:'fail',message:e.message})}}
let cookie;
await check('real preview D1 read persists seeded evidence',async()=>{const a=await call('snapshot'),b=await call('snapshot');assert.equal(a.status,200);assert.equal(a.body.data.metrics.length,9);assert.equal(a.body.data.hash,b.body.data.hash)});
await check('visitor adviser rejected 401',async()=>assert.equal((await call('adviser','POST',{question:'PUE?'})).status,401));
await check('forged client identity stripped by preview middleware',async()=>assert.equal((await call('adviser','POST',{question:'PUE?'},{'oai-authenticated-user-id':'fake','oai-authenticated-user-email':'fake@example.test'})).status,401));
await check('visitor mutation rejected 401',async()=>assert.equal((await call('design','PATCH',{expected_revision:1,reason:'Test revision',inputs:{pue:1.4}})).status,401));
await check('read-only scenario returns exact energy and common workload, under one second',async()=>{const r=await call('scenarios/evaluate','POST',{inputs:{pue:1.4},include_sensitivity:true});assert.equal(r.status,200);assert.equal(r.body.data.custom.energy.annualGwh,245.28);assert.ok(r.ms<1000);assert.ok(r.body.meta.input_hash)});
await check('scenario invalid fields and stale revision rejected',async()=>{assert.equal((await call('scenarios/evaluate','POST',{inputs:{role:'admin'}})).status,400);assert.equal((await call('scenarios/evaluate','POST',{inputs:{},expected_revision:999})).status,409)});
await check('cross-origin mutations rejected 403',async()=>assert.equal((await call('register','POST',{course_section:'test',rules_agreed:true},{Origin:'https://foreign.example'})).status,403));
await check('local simulated SIWC sign-in and unregistered 403',async()=>{const r=await fetch(origin+'/signin-with-chatgpt?return_to=%2Fadviser',{redirect:'manual'});cookie=r.headers.get('set-cookie').split(';')[0];const me=await call('me','GET',undefined,{Cookie:cookie});if(me.body.data.registered)tests.push({name:'unregistered 403 observed on first fresh test run',status:'pass'});else assert.equal((await call('adviser','POST',{question:'PUE?'},{Cookie:cookie})).status,403)});
await check('registration rejects browser role spoof',async()=>assert.equal((await call('register','POST',{course_section:'test',rules_agreed:true,role:'admin'},{Cookie:cookie})).status,400));
await check('registration is persistent/idempotent and viewer-only',async()=>{const a=await call('register','POST',{course_section:'test',rules_agreed:true},{Cookie:cookie}),b=await call('register','POST',{course_section:'test',rules_agreed:true},{Cookie:cookie});assert.equal(a.status,200);assert.equal(a.body.data.id,b.body.data.id);assert.equal(a.body.data.role,'viewer');assert.equal((await call('me','GET',undefined,{Cookie:cookie})).body.data.registered,true)});
await check('viewer evidence refresh and role changes forbidden',async()=>{assert.equal((await call('evidence/refresh','POST',{adapter_id:'worldbank-renewables'},{Cookie:cookie})).status,403);assert.equal((await call('users/fake/role','PATCH',{role:'admin'},{Cookie:cookie})).status,403)});
await check('registered adviser validates input or honestly reports missing provider',async()=>{const m=await call('me','GET',undefined,{Cookie:cookie});if(m.body.data.ai_available)assert.equal((await call('adviser','POST',{question:''},{Cookie:cookie})).status,400);else assert.equal((await call('adviser','POST',{question:'PUE?'},{Cookie:cookie})).status,503);});
const report={environment:'real local Vinext + D1; SIWC identity simulated by supported preview middleware; no real OpenAI calls',origin,at:new Date().toISOString(),tests};fs.writeFileSync('reports/tests/preview-integration.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(tests.some(x=>x.status==='fail'))process.exitCode=1;
